/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TAdvogado;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Advogados que atuam em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TAdvogadoRecord extends UpdatableRecordImpl<TAdvogadoRecord> implements Record4<Integer, String, Integer, String> {

    private static final long serialVersionUID = -1191674944;

    /**
     * Create a detached TAdvogadoRecord
     */
    public TAdvogadoRecord() {
        super(TAdvogado.T_ADVOGADO);
    }

    /**
     * Create a detached, initialised TAdvogadoRecord
     */
    public TAdvogadoRecord(Integer numAdvogado, String nomAdvogado, Integer numOab, String sigUfOab) {
        super(TAdvogado.T_ADVOGADO);

        setValue(0, numAdvogado);
        setValue(1, nomAdvogado);
        setValue(2, numOab);
        setValue(3, sigUfOab);
    }

    /**
     * Getter for <code>procjud.t_advogado.num_advogado</code>. Numero de identificacao do Advogado
     */
    public Integer getNumAdvogado() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_advogado.num_advogado</code>. Numero de identificacao do Advogado
     */
    public void setNumAdvogado(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_advogado.nom_advogado</code>. Nome Completo do Advogado
     */
    public String getNomAdvogado() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_advogado.nom_advogado</code>. Nome Completo do Advogado
     */
    public void setNomAdvogado(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_advogado.num_oab</code>. Numero de inscricao do advogado na OAB
     */
    public Integer getNumOab() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_advogado.num_oab</code>. Numero de inscricao do advogado na OAB
     */
    public void setNumOab(Integer value) {
        setValue(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_advogado.sig_uf_oab</code>. Sigla da UF da OAB onde o Advogado esta registrado
     */
    public String getSigUfOab() {
        return (String) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_advogado.sig_uf_oab</code>. Sigla da UF da OAB onde o Advogado esta registrado
     */
    public void setSigUfOab(String value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TAdvogado.T_ADVOGADO.NUM_ADVOGADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TAdvogado.T_ADVOGADO.NOM_ADVOGADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TAdvogado.T_ADVOGADO.NUM_OAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TAdvogado.T_ADVOGADO.SIG_UF_OAB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getNumAdvogado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomAdvogado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNumOab();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSigUfOab();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogadoRecord value1(Integer value) {
        setNumAdvogado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogadoRecord value2(String value) {
        setNomAdvogado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogadoRecord value3(Integer value) {
        setNumOab(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogadoRecord value4(String value) {
        setSigUfOab(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogadoRecord values(Integer value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
