/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TClasseProcessual;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Classes Processuais classificam o processo judicial de acordo com o tipo 
 * de causa que se discute
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TClasseProcessualRecord extends UpdatableRecordImpl<TClasseProcessualRecord> implements Record6<String, String, Integer, String, String, Boolean> {

	private static final long serialVersionUID = -79015279;

	/**
	 * Create a detached TClasseProcessualRecord
	 */
	public TClasseProcessualRecord() {
		super(TClasseProcessual.T_CLASSE_PROCESSUAL);
	}

	/**
	 * Create a detached, initialised TClasseProcessualRecord
	 */
	public TClasseProcessualRecord(String sigClasse, String nomClasse, Integer numClasseCnj, String nomPoloAtivo, String nomPoloPassivo, Boolean indFaseInicial) {
		super(TClasseProcessual.T_CLASSE_PROCESSUAL);

		setValue(0, sigClasse);
		setValue(1, nomClasse);
		setValue(2, numClasseCnj);
		setValue(3, nomPoloAtivo);
		setValue(4, nomPoloPassivo);
		setValue(5, indFaseInicial);
	}

	/**
	 * Getter for <code>procjud.t_classe_processual.sig_classe</code>. Sigla identificadora da classe
	 */
	public String getSigClasse() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_classe_processual.sig_classe</code>. Sigla identificadora da classe
	 */
	public void setSigClasse(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>procjud.t_classe_processual.nom_classe</code>. Nome completo da classe
	 */
	public String getNomClasse() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>procjud.t_classe_processual.nom_classe</code>. Nome completo da classe
	 */
	public void setNomClasse(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>procjud.t_classe_processual.num_classe_cnj</code>. Numeracao da classe segundo classificacao do CNJ
	 */
	public Integer getNumClasseCnj() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>procjud.t_classe_processual.num_classe_cnj</code>. Numeracao da classe segundo classificacao do CNJ
	 */
	public void setNumClasseCnj(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>procjud.t_classe_processual.nom_polo_ativo</code>. Designacao dada ao polo ativo da causa (o autor)
	 */
	public String getNomPoloAtivo() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>procjud.t_classe_processual.nom_polo_ativo</code>. Designacao dada ao polo ativo da causa (o autor)
	 */
	public void setNomPoloAtivo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>procjud.t_classe_processual.nom_polo_passivo</code>. Designacao dada ao polo passivo da causa (o reu)
	 */
	public String getNomPoloPassivo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>procjud.t_classe_processual.nom_polo_passivo</code>. Designacao dada ao polo passivo da causa (o reu)
	 */
	public void setNomPoloPassivo(String value) {
		setValue(4, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_classe_processual.ind_fase_inicial</code>. Indica se a classe e atribuida na fase inicial do processo, ou diz respeito a fases de recursos
	 */
	public Boolean getIndFaseInicial() {
		return (Boolean) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_classe_processual.ind_fase_inicial</code>. Indica se a classe e atribuida na fase inicial do processo, ou diz respeito a fases de recursos
	 */
	public void setIndFaseInicial(Boolean value) {
		setValue(5, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, String, String, Boolean> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, String, String, Boolean> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.SIG_CLASSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.NOM_CLASSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.NUM_CLASSE_CNJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.NOM_POLO_ATIVO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.NOM_POLO_PASSIVO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TClasseProcessual.T_CLASSE_PROCESSUAL.IND_FASE_INICIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSigClasse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNomClasse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNumClasseCnj();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNomPoloAtivo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getNomPoloPassivo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIndFaseInicial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value1(String value) {
		setSigClasse(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value2(String value) {
		setNomClasse(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value3(Integer value) {
		setNumClasseCnj(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value4(String value) {
		setNomPoloAtivo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value5(String value) {
		setNomPoloPassivo(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord value6(Boolean value) {
		setIndFaseInicial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessualRecord values(String value1, String value2, Integer value3, String value4, String value5, Boolean value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}
}
