/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TComposicaoOj;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Composicao dos Orgaos Judicantes: relaciona os magistrados com os OJs, 
 * indicando a data de inicio e termino da atuacao do Magistrados naquele 
 * OJ
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TComposicaoOjRecord extends UpdatableRecordImpl<TComposicaoOjRecord> implements Record5<String, Date, Date, Boolean, String> {

	private static final long serialVersionUID = -840850691;

	/**
	 * Create a detached TComposicaoOjRecord
	 */
	public TComposicaoOjRecord() {
		super(TComposicaoOj.T_COMPOSICAO_OJ);
	}

	/**
	 * Create a detached, initialised TComposicaoOjRecord
	 */
	public TComposicaoOjRecord(String codMagistrado, Date dtaIniAtuacao, Date dtaTerAtuacao, Boolean indPresidente, String sigOj) {
		super(TComposicaoOj.T_COMPOSICAO_OJ);

		setValue(0, codMagistrado);
		setValue(1, dtaIniAtuacao);
		setValue(2, dtaTerAtuacao);
		setValue(3, indPresidente);
		setValue(4, sigOj);
	}

	/**
	 * Getter for <code>procjud.t_composicao_oj.cod_magistrado</code>. Codigo Identificador do Magistrado
	 */
	public String getCodMagistrado() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_composicao_oj.cod_magistrado</code>. Codigo Identificador do Magistrado
	 */
	public void setCodMagistrado(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>procjud.t_composicao_oj.dta_ini_atuacao</code>. Data de inicio da atuacao do Magistrado no OJ
	 */
	public Date getDtaIniAtuacao() {
		return (Date) getValue(1);
	}

	/**
	 * Setter for <code>procjud.t_composicao_oj.dta_ini_atuacao</code>. Data de inicio da atuacao do Magistrado no OJ
	 */
	public void setDtaIniAtuacao(Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>procjud.t_composicao_oj.dta_ter_atuacao</code>. Data de termino da atuacao do Magistrado no OJ
	 */
	public Date getDtaTerAtuacao() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>procjud.t_composicao_oj.dta_ter_atuacao</code>. Data de termino da atuacao do Magistrado no OJ
	 */
	public void setDtaTerAtuacao(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>procjud.t_composicao_oj.ind_presidente</code>. Indica se o magistrado e o presidente do respectivo OJ
	 */
	public Boolean getIndPresidente() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>procjud.t_composicao_oj.ind_presidente</code>. Indica se o magistrado e o presidente do respectivo OJ
	 */
	public void setIndPresidente(Boolean value) {
		setValue(3, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_composicao_oj.sig_oj</code>. sigla do orgao judicante
	 */
	public String getSigOj() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_composicao_oj.sig_oj</code>. sigla do orgao judicante
	 */
	public void setSigOj(String value) {
		setValue(4, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, String> key() {
		return (Record2) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Date, Date, Boolean, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Date, Date, Boolean, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TComposicaoOj.T_COMPOSICAO_OJ.COD_MAGISTRADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field2() {
		return TComposicaoOj.T_COMPOSICAO_OJ.DTA_INI_ATUACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return TComposicaoOj.T_COMPOSICAO_OJ.DTA_TER_ATUACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return TComposicaoOj.T_COMPOSICAO_OJ.IND_PRESIDENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TComposicaoOj.T_COMPOSICAO_OJ.SIG_OJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCodMagistrado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value2() {
		return getDtaIniAtuacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getDtaTerAtuacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getIndPresidente();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSigOj();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord value1(String value) {
		setCodMagistrado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord value2(Date value) {
		setDtaIniAtuacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord value3(Date value) {
		setDtaTerAtuacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord value4(Boolean value) {
		setIndPresidente(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord value5(String value) {
		setSigOj(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOjRecord values(String value1, Date value2, Date value3, Boolean value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}
}
