/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TDistribuidor;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Responsavel pela realizacao de uma distribuicao de processo
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TDistribuidorRecord extends UpdatableRecordImpl<TDistribuidorRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1933179158;

    /**
     * Create a detached TDistribuidorRecord
     */
    public TDistribuidorRecord() {
        super(TDistribuidor.T_DISTRIBUIDOR);
    }

    /**
     * Create a detached, initialised TDistribuidorRecord
     */
    public TDistribuidorRecord(String codDistribuidor, String nomDistribuidor) {
        super(TDistribuidor.T_DISTRIBUIDOR);

        setValue(0, codDistribuidor);
        setValue(1, nomDistribuidor);
    }

    /**
     * Getter for <code>procjud.t_distribuidor.cod_distribuidor</code>. Codigo que identifica o distribuidor do processo
     */
    public String getCodDistribuidor() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_distribuidor.cod_distribuidor</code>. Codigo que identifica o distribuidor do processo
     */
    public void setCodDistribuidor(String value) {
        setValue(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_distribuidor.nom_distribuidor</code>. Nome do distribuidor
     */
    public String getNomDistribuidor() {
        return (String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_distribuidor.nom_distribuidor</code>. Nome do distribuidor
     */
    public void setNomDistribuidor(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TDistribuidor.T_DISTRIBUIDOR.COD_DISTRIBUIDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDistribuidor.T_DISTRIBUIDOR.NOM_DISTRIBUIDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCodDistribuidor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomDistribuidor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDistribuidorRecord value1(String value) {
        setCodDistribuidor(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TDistribuidorRecord value2(String value) {
        setNomDistribuidor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDistribuidorRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
