/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TFaseProcessual;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Fases pelas quais passou um processo judicial. Um processo pode passar
 * por varias fases. Para cada fase, pode ser atribuida uma classe processual
 * diferente.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TFaseProcessualRecord extends UpdatableRecordImpl<TFaseProcessualRecord> implements Record7<Long, Date, String, Date, String, Byte, String> {

    private static final long serialVersionUID = 1231186772;

    /**
     * Create a detached TFaseProcessualRecord
     */
    public TFaseProcessualRecord() {
        super(TFaseProcessual.T_FASE_PROCESSUAL);
    }

    /**
     * Create a detached, initialised TFaseProcessualRecord
     */
    public TFaseProcessualRecord(Long codProcesso, Date dtaInicioFase, String sigClasse, Date dtaTerminoFase, String codMagistrado, Byte codMotivoRedist, String sigOj) {
        super(TFaseProcessual.T_FASE_PROCESSUAL);

        setValue(0, codProcesso);
        setValue(1, dtaInicioFase);
        setValue(2, sigClasse);
        setValue(3, dtaTerminoFase);
        setValue(4, codMagistrado);
        setValue(5, codMotivoRedist);
        setValue(6, sigOj);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.cod_processo</code>. Codigo do processo judicial
     */
    public Long getCodProcesso() {
        return (Long) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.cod_processo</code>. Codigo do processo judicial
     */
    public void setCodProcesso(Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.dta_inicio_fase</code>. Data de inicio da fase
     */
    public Date getDtaInicioFase() {
        return (Date) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.dta_inicio_fase</code>. Data de inicio da fase
     */
    public void setDtaInicioFase(Date value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.sig_classe</code>. Sigla identificadora da classe processual para a respectiva fase
     */
    public String getSigClasse() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.sig_classe</code>. Sigla identificadora da classe processual para a respectiva fase
     */
    public void setSigClasse(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.dta_termino_fase</code>. Data de termino da fase do processo
     */
    public Date getDtaTerminoFase() {
        return (Date) getValue(3);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.dta_termino_fase</code>. Data de termino da fase do processo
     */
    public void setDtaTerminoFase(Date value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.cod_magistrado</code>. Codigo Identificador do Magistrado para qual o processo foi distribuido. Valor nulo se o processo nao foi distribuido.
     */
    public String getCodMagistrado() {
        return (String) getValue(4);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.cod_magistrado</code>. Codigo Identificador do Magistrado para qual o processo foi distribuido. Valor nulo se o processo nao foi distribuido.
     */
    public void setCodMagistrado(String value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>procjud.t_fase_processual.cod_motivo_redist</code>. Codigo do motivo da redistribuicao. Valor nulo se o processo nao foi redistribuido na fase.
     */
    public Byte getCodMotivoRedist() {
        return (Byte) getValue(5);
    }

    /**
     * Setter for <code>procjud.t_fase_processual.cod_motivo_redist</code>. Codigo do motivo da redistribuicao. Valor nulo se o processo nao foi redistribuido na fase.
     */
    public void setCodMotivoRedist(Byte value) {
        setValue(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_fase_processual.sig_oj</code>.
     */
    public String getSigOj() {
        return (String) getValue(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_fase_processual.sig_oj</code>.
     */
    public void setSigOj(String value) {
        setValue(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Long, Date, String> key() {
        return (Record3) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Date, String, Date, String, Byte, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Date, String, Date, String, Byte, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TFaseProcessual.T_FASE_PROCESSUAL.COD_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return TFaseProcessual.T_FASE_PROCESSUAL.DTA_INICIO_FASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TFaseProcessual.T_FASE_PROCESSUAL.SIG_CLASSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return TFaseProcessual.T_FASE_PROCESSUAL.DTA_TERMINO_FASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TFaseProcessual.T_FASE_PROCESSUAL.COD_MAGISTRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TFaseProcessual.T_FASE_PROCESSUAL.COD_MOTIVO_REDIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TFaseProcessual.T_FASE_PROCESSUAL.SIG_OJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCodProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getDtaInicioFase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSigClasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getDtaTerminoFase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCodMagistrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getCodMotivoRedist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSigOj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value1(Long value) {
        setCodProcesso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value2(Date value) {
        setDtaInicioFase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value3(String value) {
        setSigClasse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value4(Date value) {
        setDtaTerminoFase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value5(String value) {
        setCodMagistrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value6(Byte value) {
        setCodMotivoRedist(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord value7(String value) {
        setSigOj(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaseProcessualRecord values(Long value1, Date value2, String value3, Date value4, String value5, Byte value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
