/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.THistDistribuicao;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Historico de distribuicões realizadas
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class THistDistribuicaoRecord extends UpdatableRecordImpl<THistDistribuicaoRecord> implements Record8<String, Integer, Long, String, Date, String, String, String> {

    private static final long serialVersionUID = -1583487367;

    /**
     * Create a detached THistDistribuicaoRecord
     */
    public THistDistribuicaoRecord() {
        super(THistDistribuicao.T_HIST_DISTRIBUICAO);
    }

    /**
     * Create a detached, initialised THistDistribuicaoRecord
     */
    public THistDistribuicaoRecord(String codDistribuidor, Integer seqDistribuicao, Long codProcesso, String codTipoDist, Date dtaDistribuicao, String codMagistrado, String txtDistribuicao, String sigOj) {
        super(THistDistribuicao.T_HIST_DISTRIBUICAO);

        setValue(0, codDistribuidor);
        setValue(1, seqDistribuicao);
        setValue(2, codProcesso);
        setValue(3, codTipoDist);
        setValue(4, dtaDistribuicao);
        setValue(5, codMagistrado);
        setValue(6, txtDistribuicao);
        setValue(7, sigOj);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.cod_distribuidor</code>. Codigo que identifica o distribuidor do processo
     */
    public String getCodDistribuidor() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.cod_distribuidor</code>. Codigo que identifica o distribuidor do processo
     */
    public void setCodDistribuidor(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.seq_distribuicao</code>. Numero sequencial da distribuicao de acordo com o Distribuidor
     */
    public Integer getSeqDistribuicao() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.seq_distribuicao</code>. Numero sequencial da distribuicao de acordo com o Distribuidor
     */
    public void setSeqDistribuicao(Integer value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.cod_processo</code>. Codigo numerico do processo distribuido
     */
    public Long getCodProcesso() {
        return (Long) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.cod_processo</code>. Codigo numerico do processo distribuido
     */
    public void setCodProcesso(Long value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.cod_tipo_dist</code>. Codigo do tipo de distribuicao
     */
    public String getCodTipoDist() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.cod_tipo_dist</code>. Codigo do tipo de distribuicao
     */
    public void setCodTipoDist(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.dta_distribuicao</code>. Data de realizacao da distribuicao do processo
     */
    public Date getDtaDistribuicao() {
        return (Date) getValue(4);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.dta_distribuicao</code>. Data de realizacao da distribuicao do processo
     */
    public void setDtaDistribuicao(Date value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.cod_magistrado</code>. Codigo Identificador do Magistrado para qual o processo foi distribuido
     */
    public String getCodMagistrado() {
        return (String) getValue(5);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.cod_magistrado</code>. Codigo Identificador do Magistrado para qual o processo foi distribuido
     */
    public void setCodMagistrado(String value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>procjud.t_hist_distribuicao.txt_distribuicao</code>. Registra detalhes da distribuicao para fins de posterior analise
     */
    public String getTxtDistribuicao() {
        return (String) getValue(6);
    }

    /**
     * Setter for <code>procjud.t_hist_distribuicao.txt_distribuicao</code>. Registra detalhes da distribuicao para fins de posterior analise
     */
    public void setTxtDistribuicao(String value) {
        setValue(6, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_hist_distribuicao.sig_oj</code>.
     */
    public String getSigOj() {
        return (String) getValue(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_hist_distribuicao.sig_oj</code>.
     */
    public void setSigOj(String value) {
        setValue(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, Long, String, Date, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, Long, String, Date, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.COD_DISTRIBUIDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.SEQ_DISTRIBUICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.COD_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.COD_TIPO_DIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.DTA_DISTRIBUICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.COD_MAGISTRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.TXT_DISTRIBUICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return THistDistribuicao.T_HIST_DISTRIBUICAO.SIG_OJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCodDistribuidor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeqDistribuicao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCodProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCodTipoDist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDtaDistribuicao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCodMagistrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTxtDistribuicao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSigOj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value1(String value) {
        setCodDistribuidor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value2(Integer value) {
        setSeqDistribuicao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value3(Long value) {
        setCodProcesso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value4(String value) {
        setCodTipoDist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value5(Date value) {
        setDtaDistribuicao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value6(String value) {
        setCodMagistrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value7(String value) {
        setTxtDistribuicao(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord value8(String value) {
        setSigOj(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicaoRecord values(String value1, Integer value2, Long value3, String value4, Date value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
