/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TImpedimentoAdvogado;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Impedimento de Magistrados em relacao a Advogados que atuam em processos
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TImpedimentoAdvogadoRecord extends UpdatableRecordImpl<TImpedimentoAdvogadoRecord> implements Record3<String, Integer, Date> {

	private static final long serialVersionUID = 1049571716;

	/**
	 * Create a detached TImpedimentoAdvogadoRecord
	 */
	public TImpedimentoAdvogadoRecord() {
		super(TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO);
	}

	/**
	 * Create a detached, initialised TImpedimentoAdvogadoRecord
	 */
	public TImpedimentoAdvogadoRecord(String codMagistrado, Integer numAdvogado, Date dtaRegistro) {
		super(TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO);

		setValue(0, codMagistrado);
		setValue(1, numAdvogado);
		setValue(2, dtaRegistro);
	}

	/**
	 * Getter for <code>procjud.t_impedimento_advogado.cod_magistrado</code>. Codigo Identificador do Magistrado
	 */
	public String getCodMagistrado() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_impedimento_advogado.cod_magistrado</code>. Codigo Identificador do Magistrado
	 */
	public void setCodMagistrado(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>procjud.t_impedimento_advogado.num_advogado</code>. Numero de identificacao do Advogado
	 */
	public Integer getNumAdvogado() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>procjud.t_impedimento_advogado.num_advogado</code>. Numero de identificacao do Advogado
	 */
	public void setNumAdvogado(Integer value) {
		setValue(1, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_impedimento_advogado.dta_registro</code>. Data de registro do impedimento
	 */
	public Date getDtaRegistro() {
		return (Date) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_impedimento_advogado.dta_registro</code>. Data de registro do impedimento
	 */
	public void setDtaRegistro(Date value) {
		setValue(2, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Integer> key() {
		return (Record2) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, Date> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, Date> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.COD_MAGISTRADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.NUM_ADVOGADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.DTA_REGISTRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCodMagistrado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNumAdvogado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getDtaRegistro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TImpedimentoAdvogadoRecord value1(String value) {
		setCodMagistrado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TImpedimentoAdvogadoRecord value2(Integer value) {
		setNumAdvogado(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TImpedimentoAdvogadoRecord value3(Date value) {
		setDtaRegistro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TImpedimentoAdvogadoRecord values(String value1, Integer value2, Date value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}
}
