/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TImpedimentoProcesso;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Impedimento de Magistrados em relacao a Processos especificos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TImpedimentoProcessoRecord extends UpdatableRecordImpl<TImpedimentoProcessoRecord> implements Record3<String, Long, Date> {

    private static final long serialVersionUID = -27980238;

    /**
     * Create a detached TImpedimentoProcessoRecord
     */
    public TImpedimentoProcessoRecord() {
        super(TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO);
    }

    /**
     * Create a detached, initialised TImpedimentoProcessoRecord
     */
    public TImpedimentoProcessoRecord(String codMagistrado, Long codProcesso, Date dtaRegistro) {
        super(TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO);

        setValue(0, codMagistrado);
        setValue(1, codProcesso);
        setValue(2, dtaRegistro);
    }

    /**
     * Getter for <code>procjud.t_impedimento_processo.cod_magistrado</code>. Codigo Identificador do Magistrado
     */
    public String getCodMagistrado() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_impedimento_processo.cod_magistrado</code>. Codigo Identificador do Magistrado
     */
    public void setCodMagistrado(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_impedimento_processo.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public Long getCodProcesso() {
        return (Long) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_impedimento_processo.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public void setCodProcesso(Long value) {
        setValue(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_impedimento_processo.dta_registro</code>. Data de registro do impedimento
     */
    public Date getDtaRegistro() {
        return (Date) getValue(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_impedimento_processo.dta_registro</code>. Data de registro do impedimento
     */
    public void setDtaRegistro(Date value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Date> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Date> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_MAGISTRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.DTA_REGISTRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCodMagistrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCodProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDtaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TImpedimentoProcessoRecord value1(String value) {
        setCodMagistrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TImpedimentoProcessoRecord value2(Long value) {
        setCodProcesso(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TImpedimentoProcessoRecord value3(Date value) {
        setDtaRegistro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TImpedimentoProcessoRecord values(String value1, Long value2, Date value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
