/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TInfoDistribuicao;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * informações com detalhes acerca de distribuições realizadas
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TInfoDistribuicaoRecord extends UpdatableRecordImpl<TInfoDistribuicaoRecord> implements Record7<Integer, Timestamp, String, String, Integer, String, String> {

    private static final long serialVersionUID = -1351065409;

    /**
     * Create a detached TInfoDistribuicaoRecord
     */
    public TInfoDistribuicaoRecord() {
        super(TInfoDistribuicao.T_INFO_DISTRIBUICAO);
    }

    /**
     * Create a detached, initialised TInfoDistribuicaoRecord
     */
    public TInfoDistribuicaoRecord(Integer seqInformacao, Timestamp dtaInformacao, String codAgente, String tipInformacao, Integer seqDistribuicao, String txtInformacao, String txtDetalhes) {
        super(TInfoDistribuicao.T_INFO_DISTRIBUICAO);

        setValue(0, seqInformacao);
        setValue(1, dtaInformacao);
        setValue(2, codAgente);
        setValue(3, tipInformacao);
        setValue(4, seqDistribuicao);
        setValue(5, txtInformacao);
        setValue(6, txtDetalhes);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.seq_informacao</code>. identificador único da informação
     */
    public Integer getSeqInformacao() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.seq_informacao</code>. identificador único da informação
     */
    public void setSeqInformacao(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.dta_informacao</code>. data de registro da informação
     */
    public Timestamp getDtaInformacao() {
        return (Timestamp) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.dta_informacao</code>. data de registro da informação
     */
    public void setDtaInformacao(Timestamp value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.cod_agente</code>. código do agente responsável pela informação
     */
    public String getCodAgente() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.cod_agente</code>. código do agente responsável pela informação
     */
    public void setCodAgente(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.tip_informacao</code>. tipo de informação registrada
     */
    public String getTipInformacao() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.tip_informacao</code>. tipo de informação registrada
     */
    public void setTipInformacao(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.seq_distribuicao</code>. número sequencial da distribuição (se houver) relativa a informação provida
     */
    public Integer getSeqDistribuicao() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.seq_distribuicao</code>. número sequencial da distribuição (se houver) relativa a informação provida
     */
    public void setSeqDistribuicao(Integer value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>procjud.t_info_distribuicao.txt_informacao</code>. texto da informação
     */
    public String getTxtInformacao() {
        return (String) getValue(5);
    }

    /**
     * Setter for <code>procjud.t_info_distribuicao.txt_informacao</code>. texto da informação
     */
    public void setTxtInformacao(String value) {
        setValue(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_info_distribuicao.txt_detalhes</code>. detalhes adicionais da informação, preenchido se necessário de acordo com o tipo de informação
     */
    public String getTxtDetalhes() {
        return (String) getValue(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_info_distribuicao.txt_detalhes</code>. detalhes adicionais da informação, preenchido se necessário de acordo com o tipo de informação
     */
    public void setTxtDetalhes(String value) {
        setValue(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, String, String, Integer, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, String, String, Integer, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.SEQ_INFORMACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.DTA_INFORMACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.COD_AGENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.TIP_INFORMACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.SEQ_DISTRIBUICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.TXT_INFORMACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TInfoDistribuicao.T_INFO_DISTRIBUICAO.TXT_DETALHES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSeqInformacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDtaInformacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCodAgente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTipInformacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSeqDistribuicao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTxtInformacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTxtDetalhes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value1(Integer value) {
        setSeqInformacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value2(Timestamp value) {
        setDtaInformacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value3(String value) {
        setCodAgente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value4(String value) {
        setTipInformacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value5(Integer value) {
        setSeqDistribuicao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value6(String value) {
        setTxtInformacao(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord value7(String value) {
        setTxtDetalhes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicaoRecord values(Integer value1, Timestamp value2, String value3, String value4, Integer value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
