/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TMagistrado;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Magistrados que atuam em Orgaos Judicantes para julgar processos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TMagistradoRecord extends UpdatableRecordImpl<TMagistradoRecord> implements Record3<String, String, Boolean> {

    private static final long serialVersionUID = 1130885496;

    /**
     * Create a detached TMagistradoRecord
     */
    public TMagistradoRecord() {
        super(TMagistrado.T_MAGISTRADO);
    }

    /**
     * Create a detached, initialised TMagistradoRecord
     */
    public TMagistradoRecord(String codMagistrado, String nomMagistrado, Boolean indAdministracao) {
        super(TMagistrado.T_MAGISTRADO);

        setValue(0, codMagistrado);
        setValue(1, nomMagistrado);
        setValue(2, indAdministracao);
    }

    /**
     * Getter for <code>procjud.t_magistrado.cod_magistrado</code>. Codigo Identificador do Magistrado
     */
    public String getCodMagistrado() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_magistrado.cod_magistrado</code>. Codigo Identificador do Magistrado
     */
    public void setCodMagistrado(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_magistrado.nom_magistrado</code>. Nome Completo do Magistrado
     */
    public String getNomMagistrado() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_magistrado.nom_magistrado</code>. Nome Completo do Magistrado
     */
    public void setNomMagistrado(String value) {
        setValue(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_magistrado.ind_administracao</code>. identifica se o magistrado é membro da administração do tribunal (presidente, vice e corregedor)
     */
    public Boolean getIndAdministracao() {
        return (Boolean) getValue(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_magistrado.ind_administracao</code>. identifica se o magistrado é membro da administração do tribunal (presidente, vice e corregedor)
     */
    public void setIndAdministracao(Boolean value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TMagistrado.T_MAGISTRADO.COD_MAGISTRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TMagistrado.T_MAGISTRADO.NOM_MAGISTRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return TMagistrado.T_MAGISTRADO.IND_ADMINISTRACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCodMagistrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomMagistrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIndAdministracao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMagistradoRecord value1(String value) {
        setCodMagistrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMagistradoRecord value2(String value) {
        setNomMagistrado(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TMagistradoRecord value3(Boolean value) {
        setIndAdministracao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMagistradoRecord values(String value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
