/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TOrgaoJudicante;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Entidade diretamente responsavel por conduzir e decidir um determinado
 * processo judicial
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TOrgaoJudicanteRecord extends UpdatableRecordImpl<TOrgaoJudicanteRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -2063852992;

    /**
     * Create a detached TOrgaoJudicanteRecord
     */
    public TOrgaoJudicanteRecord() {
        super(TOrgaoJudicante.T_ORGAO_JUDICANTE);
    }

    /**
     * Create a detached, initialised TOrgaoJudicanteRecord
     */
    public TOrgaoJudicanteRecord(String sigOj, String desOj) {
        super(TOrgaoJudicante.T_ORGAO_JUDICANTE);

        setValue(0, sigOj);
        setValue(1, desOj);
    }

    /**
     * Getter for <code>procjud.t_orgao_judicante.sig_oj</code>. Sigla identificadora do Orgao Judicante
     */
    public String getSigOj() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_orgao_judicante.sig_oj</code>. Sigla identificadora do Orgao Judicante
     */
    public void setSigOj(String value) {
        setValue(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_orgao_judicante.des_oj</code>. Descricao do Orgao Judicante
     */
    public String getDesOj() {
        return (String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_orgao_judicante.des_oj</code>. Descricao do Orgao Judicante
     */
    public void setDesOj(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TOrgaoJudicante.T_ORGAO_JUDICANTE.SIG_OJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TOrgaoJudicante.T_ORGAO_JUDICANTE.DES_OJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSigOj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDesOj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrgaoJudicanteRecord value1(String value) {
        setSigOj(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrgaoJudicanteRecord value2(String value) {
        setDesOj(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrgaoJudicanteRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
