/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TParte;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Partes do Processo Judicial
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TParteRecord extends UpdatableRecordImpl<TParteRecord> implements Record5<Long, String, String, Long, Long> {

    private static final long serialVersionUID = -713965127;

    /**
     * Create a detached TParteRecord
     */
    public TParteRecord() {
        super(TParte.T_PARTE);
    }

    /**
     * Create a detached, initialised TParteRecord
     */
    public TParteRecord(Long codParte, String nomParte, String tipParte, Long numCnpj, Long numCpf) {
        super(TParte.T_PARTE);

        setValue(0, codParte);
        setValue(1, nomParte);
        setValue(2, tipParte);
        setValue(3, numCnpj);
        setValue(4, numCpf);
    }

    /**
     * Getter for <code>procjud.t_parte.cod_parte</code>. Codigo identificador da parte
     */
    public Long getCodParte() {
        return (Long) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_parte.cod_parte</code>. Codigo identificador da parte
     */
    public void setCodParte(Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_parte.nom_parte</code>. Nome completo da parte
     */
    public String getNomParte() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_parte.nom_parte</code>. Nome completo da parte
     */
    public void setNomParte(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_parte.tip_parte</code>. Tipo da Parte: F - pessoa Fisica, J - pessoa Juridica
     */
    public String getTipParte() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_parte.tip_parte</code>. Tipo da Parte: F - pessoa Fisica, J - pessoa Juridica
     */
    public void setTipParte(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>procjud.t_parte.num_cnpj</code>. Numero do CNPJ se pessoa juridica
     */
    public Long getNumCnpj() {
        return (Long) getValue(3);
    }

    /**
     * Setter for <code>procjud.t_parte.num_cnpj</code>. Numero do CNPJ se pessoa juridica
     */
    public void setNumCnpj(Long value) {
        setValue(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_parte.num_cpf</code>. Numero do CPF se pessoa fisica
     */
    public Long getNumCpf() {
        return (Long) getValue(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_parte.num_cpf</code>. Numero do CPF se pessoa fisica
     */
    public void setNumCpf(Long value) {
        setValue(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TParte.T_PARTE.COD_PARTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TParte.T_PARTE.NOM_PARTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TParte.T_PARTE.TIP_PARTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TParte.T_PARTE.NUM_CNPJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TParte.T_PARTE.NUM_CPF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCodParte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomParte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTipParte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getNumCnpj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getNumCpf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord value1(Long value) {
        setCodParte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord value2(String value) {
        setNomParte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord value3(String value) {
        setTipParte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord value4(Long value) {
        setNumCnpj(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord value5(Long value) {
        setNumCpf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TParteRecord values(Long value1, String value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
