/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TProcurador;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Procuradores que atuam em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcuradorRecord extends UpdatableRecordImpl<TProcuradorRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -775853650;

    /**
     * Create a detached TProcuradorRecord
     */
    public TProcuradorRecord() {
        super(TProcurador.T_PROCURADOR);
    }

    /**
     * Create a detached, initialised TProcuradorRecord
     */
    public TProcuradorRecord(Integer numProcurador, String nomProcurador, String nomProcuradoria) {
        super(TProcurador.T_PROCURADOR);

        setValue(0, numProcurador);
        setValue(1, nomProcurador);
        setValue(2, nomProcuradoria);
    }

    /**
     * Getter for <code>procjud.t_procurador.num_procurador</code>. Numero identificador do procurador
     */
    public Integer getNumProcurador() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_procurador.num_procurador</code>. Numero identificador do procurador
     */
    public void setNumProcurador(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_procurador.nom_procurador</code>. Nome completo do procurador
     */
    public String getNomProcurador() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_procurador.nom_procurador</code>. Nome completo do procurador
     */
    public void setNomProcurador(String value) {
        setValue(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_procurador.nom_procuradoria</code>. Nome da procuradoria pela qual o procurador atua
     */
    public String getNomProcuradoria() {
        return (String) getValue(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_procurador.nom_procuradoria</code>. Nome da procuradoria pela qual o procurador atua
     */
    public void setNomProcuradoria(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TProcurador.T_PROCURADOR.NUM_PROCURADOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TProcurador.T_PROCURADOR.NOM_PROCURADOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TProcurador.T_PROCURADOR.NOM_PROCURADORIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getNumProcurador();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNomProcurador();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNomProcuradoria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcuradorRecord value1(Integer value) {
        setNumProcurador(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcuradorRecord value2(String value) {
        setNomProcurador(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcuradorRecord value3(String value) {
        setNomProcuradoria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcuradorRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
