/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TProcesso;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * Processos Judiciais Autuados. Os processos possuem uma identificacao interna
 * COD_PROCESSO utilizada no banco de dados e uma identificacao padrao (numeracao
 * unica) utilizada em todos os ramos do Poder Judiciario. A identificacao
 * padrao e utilizada desde jan/2010 no TST e possui o formato numerico de
 * 20 digitos NNNNNNN-DD.AAAA.J.TR.OOOO
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcessoRecord extends UpdatableRecordImpl<TProcessoRecord> implements Record8<Long, Integer, Byte, Short, Byte, Byte, Short, Date> {

    private static final long serialVersionUID = 1549897003;

    /**
     * Create a detached TProcessoRecord
     */
    public TProcessoRecord() {
        super(TProcesso.T_PROCESSO);
    }

    /**
     * Create a detached, initialised TProcessoRecord
     */
    public TProcessoRecord(Long codProcesso, Integer numProcesso, Byte numDigito, Short anoProcesso, Byte numSegmento, Byte numTribunal, Short numOrigem, Date dtaAutuacao) {
        super(TProcesso.T_PROCESSO);

        setValue(0, codProcesso);
        setValue(1, numProcesso);
        setValue(2, numDigito);
        setValue(3, anoProcesso);
        setValue(4, numSegmento);
        setValue(5, numTribunal);
        setValue(6, numOrigem);
        setValue(7, dtaAutuacao);
    }

    /**
     * Getter for <code>procjud.t_processo.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public Long getCodProcesso() {
        return (Long) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_processo.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public void setCodProcesso(Long value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>procjud.t_processo.num_processo</code>. NNNNNNN -  numero de ordem de autuacao do processo, no ano de autuacao e na unidade jurisdicional de origem
     */
    public Integer getNumProcesso() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for <code>procjud.t_processo.num_processo</code>. NNNNNNN -  numero de ordem de autuacao do processo, no ano de autuacao e na unidade jurisdicional de origem
     */
    public void setNumProcesso(Integer value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>procjud.t_processo.num_digito</code>. DD - digitos verificadores da integridade do numero do processo.
     */
    public Byte getNumDigito() {
        return (Byte) getValue(2);
    }

    /**
     * Setter for <code>procjud.t_processo.num_digito</code>. DD - digitos verificadores da integridade do numero do processo.
     */
    public void setNumDigito(Byte value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>procjud.t_processo.ano_processo</code>. AAAA - ano da ajuizamento do processo
     */
    public Short getAnoProcesso() {
        return (Short) getValue(3);
    }

    /**
     * Setter for <code>procjud.t_processo.ano_processo</code>. AAAA - ano da ajuizamento do processo
     */
    public void setAnoProcesso(Short value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>procjud.t_processo.num_segmento</code>. J - digito identificador do segmento do Judiciario a que pertence o processo. 1 - STF, 2 - CNJ, 3 - STJ, 4 - JF, 5 - JT, 6 - JE, 7 - JM da Uniao, 8 - Justica dos Estados e do DF, 9 JM Estadual
     */
    public Byte getNumSegmento() {
        return (Byte) getValue(4);
    }

    /**
     * Setter for <code>procjud.t_processo.num_segmento</code>. J - digito identificador do segmento do Judiciario a que pertence o processo. 1 - STF, 2 - CNJ, 3 - STJ, 4 - JF, 5 - JT, 6 - JE, 7 - JM da Uniao, 8 - Justica dos Estados e do DF, 9 JM Estadual
     */
    public void setNumSegmento(Byte value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>procjud.t_processo.num_tribunal</code>. TR - tribunal ou conselho do segmento do Poder Judiciario a que pertence o processo; para os tribunais superiores (STF, STJ, TST, TSE e STM) e o CNJ, o codigo devera ser preenchido com zero (00), para os Conselhos da Justica Federal e Superior da Justica do Trabalho, devera ser preenchido com o numero 90 (noventa), para os demais tribunais, com um numero identificador do tribunal
     */
    public Byte getNumTribunal() {
        return (Byte) getValue(5);
    }

    /**
     * Setter for <code>procjud.t_processo.num_tribunal</code>. TR - tribunal ou conselho do segmento do Poder Judiciario a que pertence o processo; para os tribunais superiores (STF, STJ, TST, TSE e STM) e o CNJ, o codigo devera ser preenchido com zero (00), para os Conselhos da Justica Federal e Superior da Justica do Trabalho, devera ser preenchido com o numero 90 (noventa), para os demais tribunais, com um numero identificador do tribunal
     */
    public void setNumTribunal(Byte value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>procjud.t_processo.num_origem</code>. OOOO - unidade de origem do processo, seguindo regras diversas para cada um dos segmentos do Judiciario, a excecao dos tribunais e conselhos, que terao esses digitos preenchidos com zero (0000)
     */
    public Short getNumOrigem() {
        return (Short) getValue(6);
    }

    /**
     * Setter for <code>procjud.t_processo.num_origem</code>. OOOO - unidade de origem do processo, seguindo regras diversas para cada um dos segmentos do Judiciario, a excecao dos tribunais e conselhos, que terao esses digitos preenchidos com zero (0000)
     */
    public void setNumOrigem(Short value) {
        setValue(6, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_processo.dta_autuacao</code>. Data de autuacao do processo
     */
    public Date getDtaAutuacao() {
        return (Date) getValue(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_processo.dta_autuacao</code>. Data de autuacao do processo
     */
    public void setDtaAutuacao(Date value) {
        setValue(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Byte, Short, Byte, Byte, Short, Date> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Byte, Short, Byte, Byte, Short, Date> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TProcesso.T_PROCESSO.COD_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TProcesso.T_PROCESSO.NUM_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TProcesso.T_PROCESSO.NUM_DIGITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return TProcesso.T_PROCESSO.ANO_PROCESSO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TProcesso.T_PROCESSO.NUM_SEGMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TProcesso.T_PROCESSO.NUM_TRIBUNAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TProcesso.T_PROCESSO.NUM_ORIGEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return TProcesso.T_PROCESSO.DTA_AUTUACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCodProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNumProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getNumDigito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getAnoProcesso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getNumSegmento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getNumTribunal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getNumOrigem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getDtaAutuacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value1(Long value) {
        setCodProcesso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value2(Integer value) {
        setNumProcesso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value3(Byte value) {
        setNumDigito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value4(Short value) {
        setAnoProcesso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value5(Byte value) {
        setNumSegmento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value6(Byte value) {
        setNumTribunal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value7(Short value) {
        setNumOrigem(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord value8(Date value) {
        setDtaAutuacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoRecord values(Long value1, Integer value2, Byte value3, Short value4, Byte value5, Byte value6, Short value7, Date value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
