/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TProcessoParte;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Relaciona as Partes interessadas em Processos Judiciais
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcessoParteRecord extends UpdatableRecordImpl<TProcessoParteRecord> implements Record2<Long, Long> {

	private static final long serialVersionUID = -1539444123;

	/**
	 * Create a detached TProcessoParteRecord
	 */
	public TProcessoParteRecord() {
		super(TProcessoParte.T_PROCESSO_PARTE);
	}

	/**
	 * Create a detached, initialised TProcessoParteRecord
	 */
	public TProcessoParteRecord(Long codProcesso, Long codParte) {
		super(TProcessoParte.T_PROCESSO_PARTE);

		setValue(0, codProcesso);
		setValue(1, codParte);
	}

	/**
	 * Getter for <code>procjud.t_processo_parte.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
	 */
	public Long getCodProcesso() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_processo_parte.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
	 */
	public void setCodProcesso(Long value) {
		setValue(0, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_processo_parte.cod_parte</code>. Codigo identificador da parte
	 */
	public Long getCodParte() {
		return (Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_processo_parte.cod_parte</code>. Codigo identificador da parte
	 */
	public void setCodParte(Long value) {
		setValue(1, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TProcessoParte.T_PROCESSO_PARTE.COD_PROCESSO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TProcessoParte.T_PROCESSO_PARTE.COD_PARTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodProcesso();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getCodParte();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoParteRecord value1(Long value) {
		setCodProcesso(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoParteRecord value2(Long value) {
		setCodParte(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoParteRecord values(Long value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}
}
