/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TProcessoRelacionado;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Identifica conexao entre Processos de forma a permitir a Distribuicao por 
 * dependência
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcessoRelacionadoRecord extends UpdatableRecordImpl<TProcessoRelacionadoRecord> implements Record3<Long, Long, Byte> {

	private static final long serialVersionUID = -1345074859;

	/**
	 * Create a detached TProcessoRelacionadoRecord
	 */
	public TProcessoRelacionadoRecord() {
		super(TProcessoRelacionado.T_PROCESSO_RELACIONADO);
	}

	/**
	 * Create a detached, initialised TProcessoRelacionadoRecord
	 */
	public TProcessoRelacionadoRecord(Long codProcesso, Long codProcessoRel, Byte codTipoRelac) {
		super(TProcessoRelacionado.T_PROCESSO_RELACIONADO);

		setValue(0, codProcesso);
		setValue(1, codProcessoRel);
		setValue(2, codTipoRelac);
	}

	/**
	 * Getter for <code>procjud.t_processo_relacionado.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
	 */
	public Long getCodProcesso() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_processo_relacionado.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
	 */
	public void setCodProcesso(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>procjud.t_processo_relacionado.cod_processo_rel</code>. Codigo numerico atribuido ao processo relacionado
	 */
	public Long getCodProcessoRel() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>procjud.t_processo_relacionado.cod_processo_rel</code>. Codigo numerico atribuido ao processo relacionado
	 */
	public void setCodProcessoRel(Long value) {
		setValue(1, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_processo_relacionado.cod_tipo_relac</code>. Codigo do tipo de relacionamento
	 */
	public Byte getCodTipoRelac() {
		return (Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_processo_relacionado.cod_tipo_relac</code>. Codigo do tipo de relacionamento
	 */
	public void setCodTipoRelac(Byte value) {
		setValue(2, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Byte> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Byte> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO_REL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field3() {
		return TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_TIPO_RELAC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodProcesso();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getCodProcessoRel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value3() {
		return getCodTipoRelac();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoRelacionadoRecord value1(Long value) {
		setCodProcesso(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoRelacionadoRecord value2(Long value) {
		setCodProcessoRel(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoRelacionadoRecord value3(Byte value) {
		setCodTipoRelac(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcessoRelacionadoRecord values(Long value1, Long value2, Byte value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}
}
