/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TProtocolo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Unidades de protocolo
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProtocoloRecord extends UpdatableRecordImpl<TProtocoloRecord> implements Record3<String, String, Byte> {

	private static final long serialVersionUID = 612022714;

	/**
	 * Create a detached TProtocoloRecord
	 */
	public TProtocoloRecord() {
		super(TProtocolo.T_PROTOCOLO);
	}

	/**
	 * Create a detached, initialised TProtocoloRecord
	 */
	public TProtocoloRecord(String codProtocolo, String nomProtocolo, Byte numTribunal) {
		super(TProtocolo.T_PROTOCOLO);

		setValue(0, codProtocolo);
		setValue(1, nomProtocolo);
		setValue(2, numTribunal);
	}

	/**
	 * Getter for <code>procjud.t_protocolo.cod_protocolo</code>. Código atribuído a unidade de protocolo
	 */
	public String getCodProtocolo() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_protocolo.cod_protocolo</code>. Código atribuído a unidade de protocolo
	 */
	public void setCodProtocolo(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>procjud.t_protocolo.nom_protocolo</code>. Nome dado a unidade de protocolo
	 */
	public String getNomProtocolo() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>procjud.t_protocolo.nom_protocolo</code>. Nome dado a unidade de protocolo
	 */
	public void setNomProtocolo(String value) {
		setValue(1, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_protocolo.num_tribunal</code>. Número do Tribunal referente ao protocolo
	 */
	public Byte getNumTribunal() {
		return (Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_protocolo.num_tribunal</code>. Número do Tribunal referente ao protocolo
	 */
	public void setNumTribunal(Byte value) {
		setValue(2, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Byte> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, Byte> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TProtocolo.T_PROTOCOLO.COD_PROTOCOLO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TProtocolo.T_PROTOCOLO.NOM_PROTOCOLO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field3() {
		return TProtocolo.T_PROTOCOLO.NUM_TRIBUNAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCodProtocolo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNomProtocolo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value3() {
		return getNumTribunal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProtocoloRecord value1(String value) {
		setCodProtocolo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProtocoloRecord value2(String value) {
		setNomProtocolo(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProtocoloRecord value3(Byte value) {
		setNumTribunal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProtocoloRecord values(String value1, String value2, Byte value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}
}
