/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TTipoDist;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Tipos de Distribuicao
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TTipoDistRecord extends UpdatableRecordImpl<TTipoDistRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1680820524;

    /**
     * Create a detached TTipoDistRecord
     */
    public TTipoDistRecord() {
        super(TTipoDist.T_TIPO_DIST);
    }

    /**
     * Create a detached, initialised TTipoDistRecord
     */
    public TTipoDistRecord(String codTipoDist, String desTipoDist) {
        super(TTipoDist.T_TIPO_DIST);

        setValue(0, codTipoDist);
        setValue(1, desTipoDist);
    }

    /**
     * Getter for <code>procjud.t_tipo_dist.cod_tipo_dist</code>. Codigo do tipo de distribuicao
     */
    public String getCodTipoDist() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>procjud.t_tipo_dist.cod_tipo_dist</code>. Codigo do tipo de distribuicao
     */
    public void setCodTipoDist(String value) {
        setValue(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>procjud.t_tipo_dist.des_tipo_dist</code>. Descricao do tipo de distribuicao
     */
    public String getDesTipoDist() {
        return (String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>procjud.t_tipo_dist.des_tipo_dist</code>. Descricao do tipo de distribuicao
     */
    public void setDesTipoDist(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TTipoDist.T_TIPO_DIST.COD_TIPO_DIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TTipoDist.T_TIPO_DIST.DES_TIPO_DIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCodTipoDist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDesTipoDist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTipoDistRecord value1(String value) {
        setCodTipoDist(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TTipoDistRecord value2(String value) {
        setDesTipoDist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTipoDistRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
