/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables.records;


import br.unb.sma.database.tables.TTipoRelacionamento;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Ttipos de relacionamento entre dois processos
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TTipoRelacionamentoRecord extends UpdatableRecordImpl<TTipoRelacionamentoRecord> implements Record2<Byte, String> {

	private static final long serialVersionUID = 405972207;

	/**
	 * Create a detached TTipoRelacionamentoRecord
	 */
	public TTipoRelacionamentoRecord() {
		super(TTipoRelacionamento.T_TIPO_RELACIONAMENTO);
	}

	/**
	 * Create a detached, initialised TTipoRelacionamentoRecord
	 */
	public TTipoRelacionamentoRecord(Byte codTipoRelac, String desTipoRelac) {
		super(TTipoRelacionamento.T_TIPO_RELACIONAMENTO);

		setValue(0, codTipoRelac);
		setValue(1, desTipoRelac);
	}

	/**
	 * Getter for <code>procjud.t_tipo_relacionamento.cod_tipo_relac</code>. Codigo do tipo de relacionamento
	 */
	public Byte getCodTipoRelac() {
		return (Byte) getValue(0);
	}

	/**
	 * Setter for <code>procjud.t_tipo_relacionamento.cod_tipo_relac</code>. Codigo do tipo de relacionamento
	 */
	public void setCodTipoRelac(Byte value) {
		setValue(0, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>procjud.t_tipo_relacionamento.des_tipo_relac</code>. Descricao do tipo de relacionamento
	 */
	public String getDesTipoRelac() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>procjud.t_tipo_relacionamento.des_tipo_relac</code>. Descricao do tipo de relacionamento
	 */
	public void setDesTipoRelac(String value) {
		setValue(1, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Byte> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Byte, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Byte, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field1() {
		return TTipoRelacionamento.T_TIPO_RELACIONAMENTO.COD_TIPO_RELAC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TTipoRelacionamento.T_TIPO_RELACIONAMENTO.DES_TIPO_RELAC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value1() {
		return getCodTipoRelac();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDesTipoRelac();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTipoRelacionamentoRecord value1(Byte value) {
		setCodTipoRelac(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTipoRelacionamentoRecord value2(String value) {
		setDesTipoRelac(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTipoRelacionamentoRecord values(Byte value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}
}
