/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import com.google.gson.Gson;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Advogados que atuam em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Advogado implements Serializable {

    private static final long serialVersionUID = -1185168508;

    private Integer numAdvogado;
    private String nomAdvogado;
    private Integer numOab;
    private String sigUfOab;

    public Advogado() {
    }

    public Advogado(Advogado value) {
        this.numAdvogado = value.numAdvogado;
        this.nomAdvogado = value.nomAdvogado;
        this.numOab = value.numOab;
        this.sigUfOab = value.sigUfOab;
    }

    public Advogado(
            Integer numAdvogado,
            String nomAdvogado,
            Integer numOab,
            String sigUfOab
    ) {
        this.numAdvogado = numAdvogado;
        this.nomAdvogado = nomAdvogado;
        this.numOab = numOab;
        this.sigUfOab = sigUfOab;
    }

    public Integer getNumAdvogado() {
        return this.numAdvogado;
    }

    public void setNumAdvogado(Integer numAdvogado) {
        this.numAdvogado = numAdvogado;
    }

    public String getNomAdvogado() {
        return this.nomAdvogado;
    }

    public void setNomAdvogado(String nomAdvogado) {
        this.nomAdvogado = nomAdvogado;
    }

    public Integer getNumOab() {
        return this.numOab;
    }

    public void setNumOab(Integer numOab) {
        this.numOab = numOab;
    }

    public String getSigUfOab() {
        return this.sigUfOab;
    }

    public void setSigUfOab(String sigUfOab) {
        this.sigUfOab = sigUfOab;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }
}
