/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Classes Processuais classificam o processo judicial de acordo com o tipo
 * de causa que se discute
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ClasseProcessual implements Serializable {

    private static final long serialVersionUID = -857008478;

    private String sigClasse;
    private String nomClasse;
    private Integer numClasseCnj;
    private String nomPoloAtivo;
    private String nomPoloPassivo;
    private Boolean indFaseInicial;

    public ClasseProcessual() {
    }

    public ClasseProcessual(ClasseProcessual value) {
        this.sigClasse = value.sigClasse;
        this.nomClasse = value.nomClasse;
        this.numClasseCnj = value.numClasseCnj;
        this.nomPoloAtivo = value.nomPoloAtivo;
        this.nomPoloPassivo = value.nomPoloPassivo;
        this.indFaseInicial = value.indFaseInicial;
    }

    public ClasseProcessual(
            String sigClasse,
            String nomClasse,
            Integer numClasseCnj,
            String nomPoloAtivo,
            String nomPoloPassivo,
            Boolean indFaseInicial
    ) {
        this.sigClasse = sigClasse;
        this.nomClasse = nomClasse;
        this.numClasseCnj = numClasseCnj;
        this.nomPoloAtivo = nomPoloAtivo;
        this.nomPoloPassivo = nomPoloPassivo;
        this.indFaseInicial = indFaseInicial;
    }

    public String getSigClasse() {
        return this.sigClasse;
    }

    public void setSigClasse(String sigClasse) {
        this.sigClasse = sigClasse;
    }

    public String getNomClasse() {
        return this.nomClasse;
    }

    public void setNomClasse(String nomClasse) {
        this.nomClasse = nomClasse;
    }

    public Integer getNumClasseCnj() {
        return this.numClasseCnj;
    }

    public void setNumClasseCnj(Integer numClasseCnj) {
        this.numClasseCnj = numClasseCnj;
    }

    public String getNomPoloAtivo() {
        return this.nomPoloAtivo;
    }

    public void setNomPoloAtivo(String nomPoloAtivo) {
        this.nomPoloAtivo = nomPoloAtivo;
    }

    public String getNomPoloPassivo() {
        return this.nomPoloPassivo;
    }

    public void setNomPoloPassivo(String nomPoloPassivo) {
        this.nomPoloPassivo = nomPoloPassivo;
    }

    public Boolean getIndFaseInicial() {
        return this.indFaseInicial;
    }

    public void setIndFaseInicial(Boolean indFaseInicial) {
        this.indFaseInicial = indFaseInicial;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClasseProcessual (");

        sb.append(sigClasse);
        sb.append(", ").append(nomClasse);
        sb.append(", ").append(numClasseCnj);
        sb.append(", ").append(nomPoloAtivo);
        sb.append(", ").append(nomPoloPassivo);
        sb.append(", ").append(indFaseInicial);

        sb.append(")");
        return sb.toString();
    }
}
