/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Mapeamento entre as Classes Processuais e os Orgaos Judicantes para onde
 * processos da classe podem ser distribuidos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Competencia implements Serializable {

    private static final long serialVersionUID = 1719688256;

    private String sigClasse;
    private String sigOj;

    public Competencia() {
    }

    public Competencia(Competencia value) {
        this.sigClasse = value.sigClasse;
        this.sigOj = value.sigOj;
    }

    public Competencia(
            String sigClasse,
            String sigOj
    ) {
        this.sigClasse = sigClasse;
        this.sigOj = sigOj;
    }

    public String getSigClasse() {
        return this.sigClasse;
    }

    public void setSigClasse(String sigClasse) {
        this.sigClasse = sigClasse;
    }

    public String getSigOj() {
        return this.sigOj;
    }

    public void setSigOj(String sigOj) {
        this.sigOj = sigOj;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Competencia (");

        sb.append(sigClasse);
        sb.append(", ").append(sigOj);

        sb.append(")");
        return sb.toString();
    }
}
