/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * Composicao dos Orgaos Judicantes: relaciona os magistrados com os OJs,
 * indicando a data de inicio e termino da atuacao do Magistrados naquele
 * OJ
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ComposicaoOj implements Serializable {

    private static final long serialVersionUID = 1599941300;

    private String codMagistrado;
    private Date dtaIniAtuacao;
    private Date dtaTerAtuacao;
    private Boolean indPresidente;
    private String sigOj;

    public ComposicaoOj() {
    }

    public ComposicaoOj(ComposicaoOj value) {
        this.codMagistrado = value.codMagistrado;
        this.dtaIniAtuacao = value.dtaIniAtuacao;
        this.dtaTerAtuacao = value.dtaTerAtuacao;
        this.indPresidente = value.indPresidente;
        this.sigOj = value.sigOj;
    }

    public ComposicaoOj(
            String codMagistrado,
            Date dtaIniAtuacao,
            Date dtaTerAtuacao,
            Boolean indPresidente,
            String sigOj
    ) {
        this.codMagistrado = codMagistrado;
        this.dtaIniAtuacao = dtaIniAtuacao;
        this.dtaTerAtuacao = dtaTerAtuacao;
        this.indPresidente = indPresidente;
        this.sigOj = sigOj;
    }

    public String getCodMagistrado() {
        return this.codMagistrado;
    }

    public void setCodMagistrado(String codMagistrado) {
        this.codMagistrado = codMagistrado;
    }

    public Date getDtaIniAtuacao() {
        return this.dtaIniAtuacao;
    }

    public void setDtaIniAtuacao(Date dtaIniAtuacao) {
        this.dtaIniAtuacao = dtaIniAtuacao;
    }

    public Date getDtaTerAtuacao() {
        return this.dtaTerAtuacao;
    }

    public void setDtaTerAtuacao(Date dtaTerAtuacao) {
        this.dtaTerAtuacao = dtaTerAtuacao;
    }

    public Boolean getIndPresidente() {
        return this.indPresidente;
    }

    public void setIndPresidente(Boolean indPresidente) {
        this.indPresidente = indPresidente;
    }

    public String getSigOj() {
        return this.sigOj;
    }

    public void setSigOj(String sigOj) {
        this.sigOj = sigOj;
    }

    @Override
    public String toString() {
        return sigOj;
    }
}
