/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * Denominacao das partes do processo em uma determinada frase. Relaciona
 * as tabela T_FASE_PROCESSUAL com T_PROCESSO_PARTE de forma a indicar qual
 * a forma de atuacao da parte na fase processual determinada.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DenParteFaseProc implements Serializable {

    private static final long serialVersionUID = -238279030;

    private Long codProcesso;
    private Long codParte;
    private Date dtaInicioFase;
    private String sigClasse;
    private Boolean indPoloAtivo;

    public DenParteFaseProc() {
    }

    public DenParteFaseProc(DenParteFaseProc value) {
        this.codProcesso = value.codProcesso;
        this.codParte = value.codParte;
        this.dtaInicioFase = value.dtaInicioFase;
        this.sigClasse = value.sigClasse;
        this.indPoloAtivo = value.indPoloAtivo;
    }

    public DenParteFaseProc(
            Long codProcesso,
            Long codParte,
            Date dtaInicioFase,
            String sigClasse,
            Boolean indPoloAtivo
    ) {
        this.codProcesso = codProcesso;
        this.codParte = codParte;
        this.dtaInicioFase = dtaInicioFase;
        this.sigClasse = sigClasse;
        this.indPoloAtivo = indPoloAtivo;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Long getCodParte() {
        return this.codParte;
    }

    public void setCodParte(Long codParte) {
        this.codParte = codParte;
    }

    public Date getDtaInicioFase() {
        return this.dtaInicioFase;
    }

    public void setDtaInicioFase(Date dtaInicioFase) {
        this.dtaInicioFase = dtaInicioFase;
    }

    public String getSigClasse() {
        return this.sigClasse;
    }

    public void setSigClasse(String sigClasse) {
        this.sigClasse = sigClasse;
    }

    public Boolean getIndPoloAtivo() {
        return this.indPoloAtivo;
    }

    public void setIndPoloAtivo(Boolean indPoloAtivo) {
        this.indPoloAtivo = indPoloAtivo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DenParteFaseProc (");

        sb.append(codProcesso);
        sb.append(", ").append(codParte);
        sb.append(", ").append(dtaInicioFase);
        sb.append(", ").append(sigClasse);
        sb.append(", ").append(indPoloAtivo);

        sb.append(")");
        return sb.toString();
    }
}
