/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Responsavel pela realizacao de uma distribuicao de processo
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Distribuidor implements Serializable {

    private static final long serialVersionUID = 58784861;

    private String codDistribuidor;
    private String nomDistribuidor;

    public Distribuidor() {
    }

    public Distribuidor(Distribuidor value) {
        this.codDistribuidor = value.codDistribuidor;
        this.nomDistribuidor = value.nomDistribuidor;
    }

    public Distribuidor(
            String codDistribuidor,
            String nomDistribuidor
    ) {
        this.codDistribuidor = codDistribuidor;
        this.nomDistribuidor = nomDistribuidor;
    }

    public String getCodDistribuidor() {
        return this.codDistribuidor;
    }

    public void setCodDistribuidor(String codDistribuidor) {
        this.codDistribuidor = codDistribuidor;
    }

    public String getNomDistribuidor() {
        return this.nomDistribuidor;
    }

    public void setNomDistribuidor(String nomDistribuidor) {
        this.nomDistribuidor = nomDistribuidor;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Distribuidor (");

        sb.append(codDistribuidor);
        sb.append(", ").append(nomDistribuidor);

        sb.append(")");
        return sb.toString();
    }
}
