/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * Fases pelas quais passou um processo judicial. Um processo pode passar
 * por varias fases. Para cada fase, pode ser atribuida uma classe processual
 * diferente.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FaseProcessual implements Serializable {

    private static final long serialVersionUID = -44566114;

    private Long codProcesso;
    private Date dtaInicioFase;
    private String sigClasse;
    private Date dtaTerminoFase;
    private String codMagistrado;
    private Byte codMotivoRedist;
    private String sigOj;

    public FaseProcessual() {
    }

    public FaseProcessual(FaseProcessual value) {
        this.codProcesso = value.codProcesso;
        this.dtaInicioFase = value.dtaInicioFase;
        this.sigClasse = value.sigClasse;
        this.dtaTerminoFase = value.dtaTerminoFase;
        this.codMagistrado = value.codMagistrado;
        this.codMotivoRedist = value.codMotivoRedist;
        this.sigOj = value.sigOj;
    }

    public FaseProcessual(
            Long codProcesso,
            Date dtaInicioFase,
            String sigClasse,
            Date dtaTerminoFase,
            String codMagistrado,
            Byte codMotivoRedist,
            String sigOj
    ) {
        this.codProcesso = codProcesso;
        this.dtaInicioFase = dtaInicioFase;
        this.sigClasse = sigClasse;
        this.dtaTerminoFase = dtaTerminoFase;
        this.codMagistrado = codMagistrado;
        this.codMotivoRedist = codMotivoRedist;
        this.sigOj = sigOj;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Date getDtaInicioFase() {
        return this.dtaInicioFase;
    }

    public void setDtaInicioFase(Date dtaInicioFase) {
        this.dtaInicioFase = dtaInicioFase;
    }

    public String getSigClasse() {
        return this.sigClasse;
    }

    public void setSigClasse(String sigClasse) {
        this.sigClasse = sigClasse;
    }

    public Date getDtaTerminoFase() {
        return this.dtaTerminoFase;
    }

    public void setDtaTerminoFase(Date dtaTerminoFase) {
        this.dtaTerminoFase = dtaTerminoFase;
    }

    public String getCodMagistrado() {
        return this.codMagistrado;
    }

    public void setCodMagistrado(String codMagistrado) {
        this.codMagistrado = codMagistrado;
    }

    public Byte getCodMotivoRedist() {
        return this.codMotivoRedist;
    }

    public void setCodMotivoRedist(Byte codMotivoRedist) {
        this.codMotivoRedist = codMotivoRedist;
    }

    public String getSigOj() {
        return this.sigOj;
    }

    public void setSigOj(String sigOj) {
        this.sigOj = sigOj;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FaseProcessual (");

        sb.append(codProcesso);
        sb.append(", ").append(dtaInicioFase);
        sb.append(", ").append(sigClasse);
        sb.append(", ").append(dtaTerminoFase);
        sb.append(", ").append(codMagistrado);
        sb.append(", ").append(codMotivoRedist);
        sb.append(", ").append(sigOj);

        sb.append(")");
        return sb.toString();
    }
}
