/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * Impedimento de Magistrados em relacao a Processos especificos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ImpedimentoProcesso implements Serializable {

    private static final long serialVersionUID = 757158557;

    private String codMagistrado;
    private Long codProcesso;
    private Date dtaRegistro;

    public ImpedimentoProcesso() {
    }

    public ImpedimentoProcesso(ImpedimentoProcesso value) {
        this.codMagistrado = value.codMagistrado;
        this.codProcesso = value.codProcesso;
        this.dtaRegistro = value.dtaRegistro;
    }

    public ImpedimentoProcesso(
            String codMagistrado,
            Long codProcesso,
            Date dtaRegistro
    ) {
        this.codMagistrado = codMagistrado;
        this.codProcesso = codProcesso;
        this.dtaRegistro = dtaRegistro;
    }

    public String getCodMagistrado() {
        return this.codMagistrado;
    }

    public void setCodMagistrado(String codMagistrado) {
        this.codMagistrado = codMagistrado;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Date getDtaRegistro() {
        return this.dtaRegistro;
    }

    public void setDtaRegistro(Date dtaRegistro) {
        this.dtaRegistro = dtaRegistro;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImpedimentoProcesso (");

        sb.append(codMagistrado);
        sb.append(", ").append(codProcesso);
        sb.append(", ").append(dtaRegistro);

        sb.append(")");
        return sb.toString();
    }
}
