/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * Impedimento de Magistrados em relacao as Partes de processos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ImpedimentoParte implements Serializable {

    private static final long serialVersionUID = -1814953291;

    private String codMagistrado;
    private Long codParte;
    private Date dtaRegistro;

    public ImpedimentoParte() {
    }

    public ImpedimentoParte(ImpedimentoParte value) {
        this.codMagistrado = value.codMagistrado;
        this.codParte = value.codParte;
        this.dtaRegistro = value.dtaRegistro;
    }

    public ImpedimentoParte(
            String codMagistrado,
            Long codParte,
            Date dtaRegistro
    ) {
        this.codMagistrado = codMagistrado;
        this.codParte = codParte;
        this.dtaRegistro = dtaRegistro;
    }

    public String getCodMagistrado() {
        return this.codMagistrado;
    }

    public void setCodMagistrado(String codMagistrado) {
        this.codMagistrado = codMagistrado;
    }

    public Long getCodParte() {
        return this.codParte;
    }

    public void setCodParte(Long codParte) {
        this.codParte = codParte;
    }

    public Date getDtaRegistro() {
        return this.dtaRegistro;
    }

    public void setDtaRegistro(Date dtaRegistro) {
        this.dtaRegistro = dtaRegistro;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImpedimentoParte (");

        sb.append(codMagistrado);
        sb.append(", ").append(codParte);
        sb.append(", ").append(dtaRegistro);

        sb.append(")");
        return sb.toString();
    }
}
