/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Relaciona os possiveis motivos para redistribuicao de um processo
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MotivoRedistribuicao implements Serializable {

    private static final long serialVersionUID = 1492259415;

    private Byte codMotivoRedist;
    private String desMotivoRedist;

    public MotivoRedistribuicao() {
    }

    public MotivoRedistribuicao(MotivoRedistribuicao value) {
        this.codMotivoRedist = value.codMotivoRedist;
        this.desMotivoRedist = value.desMotivoRedist;
    }

    public MotivoRedistribuicao(
            Byte codMotivoRedist,
            String desMotivoRedist
    ) {
        this.codMotivoRedist = codMotivoRedist;
        this.desMotivoRedist = desMotivoRedist;
    }

    public Byte getCodMotivoRedist() {
        return this.codMotivoRedist;
    }

    public void setCodMotivoRedist(Byte codMotivoRedist) {
        this.codMotivoRedist = codMotivoRedist;
    }

    public String getDesMotivoRedist() {
        return this.desMotivoRedist;
    }

    public void setDesMotivoRedist(String desMotivoRedist) {
        this.desMotivoRedist = desMotivoRedist;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MotivoRedistribuicao (");

        sb.append(codMotivoRedist);
        sb.append(", ").append(desMotivoRedist);

        sb.append(")");
        return sb.toString();
    }
}
