/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Entidade diretamente responsavel por conduzir e decidir um determinado
 * processo judicial
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OrgaoJudicante implements Serializable {

    private static final long serialVersionUID = 848669427;

    private String sigOj;
    private String desOj;

    public OrgaoJudicante() {
    }

    public OrgaoJudicante(OrgaoJudicante value) {
        this.sigOj = value.sigOj;
        this.desOj = value.desOj;
    }

    public OrgaoJudicante(
            String sigOj,
            String desOj
    ) {
        this.sigOj = sigOj;
        this.desOj = desOj;
    }

    public String getSigOj() {
        return this.sigOj;
    }

    public void setSigOj(String sigOj) {
        this.sigOj = sigOj;
    }

    public String getDesOj() {
        return this.desOj;
    }

    public void setDesOj(String desOj) {
        this.desOj = desOj;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrgaoJudicante (");

        sb.append(sigOj);
        sb.append(", ").append(desOj);

        sb.append(")");
        return sb.toString();
    }
}
