/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import com.google.gson.Gson;

import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Partes do Processo Judicial
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Parte implements Serializable {

    private static final long serialVersionUID = 1011098910;

    private Long codParte;
    private String nomParte;
    private String tipParte;
    private Long numCnpj;
    private Long numCpf;

    public Parte() {
    }

    public Parte(Parte value) {
        this.codParte = value.codParte;
        this.nomParte = value.nomParte;
        this.tipParte = value.tipParte;
        this.numCnpj = value.numCnpj;
        this.numCpf = value.numCpf;
    }

    public Parte(
            Long codParte,
            String nomParte,
            String tipParte,
            Long numCnpj,
            Long numCpf
    ) {
        this.codParte = codParte;
        this.nomParte = nomParte;
        this.tipParte = tipParte;
        this.numCnpj = numCnpj;
        this.numCpf = numCpf;
    }

    public Long getCodParte() {
        return this.codParte;
    }

    public void setCodParte(Long codParte) {
        this.codParte = codParte;
    }

    public String getNomParte() {
        return this.nomParte;
    }

    public void setNomParte(String nomParte) {
        this.nomParte = nomParte;
    }

    public String getTipParte() {
        return this.tipParte;
    }

    public void setTipParte(String tipParte) {
        this.tipParte = tipParte;
    }

    public Long getNumCnpj() {
        return this.numCnpj;
    }

    public void setNumCnpj(Long numCnpj) {
        this.numCnpj = numCnpj;
    }

    public Long getNumCpf() {
        return this.numCpf;
    }

    public void setNumCpf(Long numCpf) {
        this.numCpf = numCpf;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }
}
