/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Identifica conexao entre Processos de forma a permitir a Distribuicao por
 * dependência
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProcessoRelacionado implements Serializable {

    private static final long serialVersionUID = 1967902802;

    private Long codProcesso;
    private Long codProcessoRel;
    private Byte codTipoRelac;

    public ProcessoRelacionado() {
    }

    public ProcessoRelacionado(ProcessoRelacionado value) {
        this.codProcesso = value.codProcesso;
        this.codProcessoRel = value.codProcessoRel;
        this.codTipoRelac = value.codTipoRelac;
    }

    public ProcessoRelacionado(
            Long codProcesso,
            Long codProcessoRel,
            Byte codTipoRelac
    ) {
        this.codProcesso = codProcesso;
        this.codProcessoRel = codProcessoRel;
        this.codTipoRelac = codTipoRelac;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Long getCodProcessoRel() {
        return this.codProcessoRel;
    }

    public void setCodProcessoRel(Long codProcessoRel) {
        this.codProcessoRel = codProcessoRel;
    }

    public Byte getCodTipoRelac() {
        return this.codTipoRelac;
    }

    public void setCodTipoRelac(Byte codTipoRelac) {
        this.codTipoRelac = codTipoRelac;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessoRelacionado (");

        sb.append(codProcesso);
        sb.append(", ").append(codProcessoRel);
        sb.append(", ").append(codTipoRelac);

        sb.append(")");
        return sb.toString();
    }
}
