/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Relaciona os Advogados das Partes interessadas em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProcessoParteAdvogado implements Serializable {

    private static final long serialVersionUID = -1643697522;

    private Long codProcesso;
    private Long codParte;
    private Integer numAdvogado;

    public ProcessoParteAdvogado() {
    }

    public ProcessoParteAdvogado(ProcessoParteAdvogado value) {
        this.codProcesso = value.codProcesso;
        this.codParte = value.codParte;
        this.numAdvogado = value.numAdvogado;
    }

    public ProcessoParteAdvogado(
            Long codProcesso,
            Long codParte,
            Integer numAdvogado
    ) {
        this.codProcesso = codProcesso;
        this.codParte = codParte;
        this.numAdvogado = numAdvogado;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Long getCodParte() {
        return this.codParte;
    }

    public void setCodParte(Long codParte) {
        this.codParte = codParte;
    }

    public Integer getNumAdvogado() {
        return this.numAdvogado;
    }

    public void setNumAdvogado(Integer numAdvogado) {
        this.numAdvogado = numAdvogado;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessoParteAdvogado (");

        sb.append(codProcesso);
        sb.append(", ").append(codParte);
        sb.append(", ").append(numAdvogado);

        sb.append(")");
        return sb.toString();
    }
}
