/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Relaciona os Procuradores das Partes interessadas em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProcessoParteProcurador implements Serializable {

    private static final long serialVersionUID = -809389409;

    private Long codProcesso;
    private Long codParte;
    private Integer numProcurador;

    public ProcessoParteProcurador() {
    }

    public ProcessoParteProcurador(ProcessoParteProcurador value) {
        this.codProcesso = value.codProcesso;
        this.codParte = value.codParte;
        this.numProcurador = value.numProcurador;
    }

    public ProcessoParteProcurador(
            Long codProcesso,
            Long codParte,
            Integer numProcurador
    ) {
        this.codProcesso = codProcesso;
        this.codParte = codParte;
        this.numProcurador = numProcurador;
    }

    public Long getCodProcesso() {
        return this.codProcesso;
    }

    public void setCodProcesso(Long codProcesso) {
        this.codProcesso = codProcesso;
    }

    public Long getCodParte() {
        return this.codParte;
    }

    public void setCodParte(Long codParte) {
        this.codParte = codParte;
    }

    public Integer getNumProcurador() {
        return this.numProcurador;
    }

    public void setNumProcurador(Integer numProcurador) {
        this.numProcurador = numProcurador;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessoParteProcurador (");

        sb.append(codProcesso);
        sb.append(", ").append(codParte);
        sb.append(", ").append(numProcurador);

        sb.append(")");
        return sb.toString();
    }
}
