/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Unidades de protocolo
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Protocolo implements Serializable {

    private static final long serialVersionUID = 7641848;

    private String codProtocolo;
    private String nomProtocolo;
    private Byte numTribunal;

    public Protocolo() {
    }

    public Protocolo(Protocolo value) {
        this.codProtocolo = value.codProtocolo;
        this.nomProtocolo = value.nomProtocolo;
        this.numTribunal = value.numTribunal;
    }

    public Protocolo(
            String codProtocolo,
            String nomProtocolo,
            Byte numTribunal
    ) {
        this.codProtocolo = codProtocolo;
        this.nomProtocolo = nomProtocolo;
        this.numTribunal = numTribunal;
    }

    public String getCodProtocolo() {
        return this.codProtocolo;
    }

    public void setCodProtocolo(String codProtocolo) {
        this.codProtocolo = codProtocolo;
    }

    public String getNomProtocolo() {
        return this.nomProtocolo;
    }

    public void setNomProtocolo(String nomProtocolo) {
        this.nomProtocolo = nomProtocolo;
    }

    public Byte getNumTribunal() {
        return this.numTribunal;
    }

    public void setNumTribunal(Byte numTribunal) {
        this.numTribunal = numTribunal;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Protocolo (");

        sb.append(codProtocolo);
        sb.append(", ").append(nomProtocolo);
        sb.append(", ").append(numTribunal);

        sb.append(")");
        return sb.toString();
    }
}
