/**
 * This class is generated by jOOQ
 */
package br.unb.sma.entities;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Tipos de Distribuicao
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TipoDist implements Serializable {

    private static final long serialVersionUID = 2084073035;

    private String codTipoDist;
    private String desTipoDist;

    public TipoDist() {
    }

    public TipoDist(TipoDist value) {
        this.codTipoDist = value.codTipoDist;
        this.desTipoDist = value.desTipoDist;
    }

    public TipoDist(
            String codTipoDist,
            String desTipoDist
    ) {
        this.codTipoDist = codTipoDist;
        this.desTipoDist = desTipoDist;
    }

    public String getCodTipoDist() {
        return this.codTipoDist;
    }

    public void setCodTipoDist(String codTipoDist) {
        this.codTipoDist = codTipoDist;
    }

    public String getDesTipoDist() {
        return this.desTipoDist;
    }

    public void setDesTipoDist(String desTipoDist) {
        this.desTipoDist = desTipoDist;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TipoDist (");

        sb.append(codTipoDist);
        sb.append(", ").append(desTipoDist);

        sb.append(")");
        return sb.toString();
    }
}
