/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database;


import br.unb.sma.database.tables.*;
import br.unb.sma.database.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>procjud</code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TAdvogadoRecord> ADVOGADO_PK = UniqueKeys0.ADVOGADO_PK;
    public static final UniqueKey<TClasseProcessualRecord> CLASSE_PROCESSUAL_PK = UniqueKeys0.CLASSE_PROCESSUAL_PK;
    public static final UniqueKey<TCompetenciaRecord> COMPETENCIA_PK = UniqueKeys0.COMPETENCIA_PK;
    public static final UniqueKey<TComposicaoOjRecord> COMPOSICAO_PK = UniqueKeys0.COMPOSICAO_PK;
    public static final UniqueKey<TDenParteFaseProcRecord> PK_T_DEN_PARTE_FASE_PROC = UniqueKeys0.PK_T_DEN_PARTE_FASE_PROC;
    public static final UniqueKey<TDistribuidorRecord> DISTRIBUIDOR_PK = UniqueKeys0.DISTRIBUIDOR_PK;
    public static final UniqueKey<TFaseProcessualRecord> PK_T_FASE_PROCESSUAL = UniqueKeys0.PK_T_FASE_PROCESSUAL;
    public static final UniqueKey<THistDistribuicaoRecord> HIST_DISTRIBUICAO_PK = UniqueKeys0.HIST_DISTRIBUICAO_PK;
    public static final UniqueKey<TImpedimentoAdvogadoRecord> IMPEDIMENTO_ADVOGADO_PK = UniqueKeys0.IMPEDIMENTO_ADVOGADO_PK;
    public static final UniqueKey<TImpedimentoParteRecord> IMPEDIMENTO_PARTE_PK = UniqueKeys0.IMPEDIMENTO_PARTE_PK;
    public static final UniqueKey<TImpedimentoProcessoRecord> IMPEDIMENTO_PROCESSO_PK = UniqueKeys0.IMPEDIMENTO_PROCESSO_PK;
    public static final UniqueKey<TMagistradoRecord> MAGISTRADO_PK = UniqueKeys0.MAGISTRADO_PK;
    public static final UniqueKey<TMotivoRedistribuicaoRecord> MOTIVO_REDISTRIBUICAO_PK = UniqueKeys0.MOTIVO_REDISTRIBUICAO_PK;
    public static final UniqueKey<TOrgaoJudicanteRecord> ORGAO_JUDICANTE_PK = UniqueKeys0.ORGAO_JUDICANTE_PK;
    public static final UniqueKey<TParteRecord> PARTE_PK = UniqueKeys0.PARTE_PK;
    public static final UniqueKey<TProcessoRecord> PROCESSO_PK = UniqueKeys0.PROCESSO_PK;
    public static final UniqueKey<TProcessoParteRecord> PROCESSO_PARTE_PK = UniqueKeys0.PROCESSO_PARTE_PK;
    public static final UniqueKey<TProcessoParteAdvogadoRecord> PROCESSO_PARTE_ADVOGADO_PK = UniqueKeys0.PROCESSO_PARTE_ADVOGADO_PK;
    public static final UniqueKey<TProcessoParteProcuradorRecord> PROCESSO_PARTE_PROCURADOR_PK = UniqueKeys0.PROCESSO_PARTE_PROCURADOR_PK;
    public static final UniqueKey<TProcessoRelacionadoRecord> PROCESSO_RELACIONADO_PK = UniqueKeys0.PROCESSO_RELACIONADO_PK;
    public static final UniqueKey<TProcuradorRecord> PROCURADOR_PK = UniqueKeys0.PROCURADOR_PK;
    public static final UniqueKey<TProtocoloRecord> PK_T_PROTOCOLO = UniqueKeys0.PK_T_PROTOCOLO;
    public static final UniqueKey<TTipoDistRecord> TIPO_DIST_PK = UniqueKeys0.TIPO_DIST_PK;
    public static final UniqueKey<TTipoRelacionamentoRecord> TIPO_RELACIONAMENTO_PK = UniqueKeys0.TIPO_RELACIONAMENTO_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TCompetenciaRecord, TClasseProcessualRecord> T_COMPETENCIA__COMPETENCIA_FK1 = ForeignKeys0.T_COMPETENCIA__COMPETENCIA_FK1;
    public static final ForeignKey<TCompetenciaRecord, TOrgaoJudicanteRecord> T_COMPETENCIA__COMPETENCIA_FK2 = ForeignKeys0.T_COMPETENCIA__COMPETENCIA_FK2;
    public static final ForeignKey<TComposicaoOjRecord, TMagistradoRecord> T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK2 = ForeignKeys0.T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK2;
    public static final ForeignKey<TComposicaoOjRecord, TOrgaoJudicanteRecord> T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK1 = ForeignKeys0.T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK1;
    public static final ForeignKey<TDenParteFaseProcRecord, TProcessoParteRecord> T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK1 = ForeignKeys0.T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK1;
    public static final ForeignKey<TDenParteFaseProcRecord, TFaseProcessualRecord> T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK2 = ForeignKeys0.T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK2;
    public static final ForeignKey<TFaseProcessualRecord, TProcessoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK5 = ForeignKeys0.T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK5;
    public static final ForeignKey<TFaseProcessualRecord, TClasseProcessualRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK1 = ForeignKeys0.T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK1;
    public static final ForeignKey<TFaseProcessualRecord, TMagistradoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK3 = ForeignKeys0.T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK3;
    public static final ForeignKey<TFaseProcessualRecord, TMotivoRedistribuicaoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK4 = ForeignKeys0.T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK4;
    public static final ForeignKey<TFaseProcessualRecord, TOrgaoJudicanteRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK2 = ForeignKeys0.T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK2;
    public static final ForeignKey<THistDistribuicaoRecord, TDistribuidorRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK1 = ForeignKeys0.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK1;
    public static final ForeignKey<THistDistribuicaoRecord, TProcessoRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK3 = ForeignKeys0.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK3;
    public static final ForeignKey<THistDistribuicaoRecord, TTipoDistRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK2 = ForeignKeys0.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK2;
    public static final ForeignKey<THistDistribuicaoRecord, TMagistradoRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK4 = ForeignKeys0.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK4;
    public static final ForeignKey<THistDistribuicaoRecord, TOrgaoJudicanteRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK5 = ForeignKeys0.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK5;
    public static final ForeignKey<TImpedimentoAdvogadoRecord, TMagistradoRecord> T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK1 = ForeignKeys0.T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK1;
    public static final ForeignKey<TImpedimentoAdvogadoRecord, TAdvogadoRecord> T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK2 = ForeignKeys0.T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK2;
    public static final ForeignKey<TImpedimentoParteRecord, TMagistradoRecord> T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK1 = ForeignKeys0.T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK1;
    public static final ForeignKey<TImpedimentoParteRecord, TParteRecord> T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK2 = ForeignKeys0.T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK2;
    public static final ForeignKey<TImpedimentoProcessoRecord, TMagistradoRecord> T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK1 = ForeignKeys0.T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK1;
    public static final ForeignKey<TImpedimentoProcessoRecord, TProcessoRecord> T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK2 = ForeignKeys0.T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK2;
    public static final ForeignKey<TProcessoParteRecord, TProcessoRecord> T_PROCESSO_PARTE__PROCESSO_PARTE_FK1 = ForeignKeys0.T_PROCESSO_PARTE__PROCESSO_PARTE_FK1;
    public static final ForeignKey<TProcessoParteRecord, TParteRecord> T_PROCESSO_PARTE__PROCESSO_PARTE_FK2 = ForeignKeys0.T_PROCESSO_PARTE__PROCESSO_PARTE_FK2;
    public static final ForeignKey<TProcessoParteAdvogadoRecord, TProcessoParteRecord> T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK1 = ForeignKeys0.T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK1;
    public static final ForeignKey<TProcessoParteAdvogadoRecord, TAdvogadoRecord> T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK2 = ForeignKeys0.T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK2;
    public static final ForeignKey<TProcessoParteProcuradorRecord, TProcessoParteRecord> T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK1 = ForeignKeys0.T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK1;
    public static final ForeignKey<TProcessoParteProcuradorRecord, TProcuradorRecord> T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK2 = ForeignKeys0.T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK2;
    public static final ForeignKey<TProcessoRelacionadoRecord, TProcessoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK1 = ForeignKeys0.T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK1;
    public static final ForeignKey<TProcessoRelacionadoRecord, TProcessoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK2 = ForeignKeys0.T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK2;
    public static final ForeignKey<TProcessoRelacionadoRecord, TTipoRelacionamentoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK3 = ForeignKeys0.T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK3;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TAdvogadoRecord> ADVOGADO_PK = createUniqueKey(TAdvogado.T_ADVOGADO, TAdvogado.T_ADVOGADO.NUM_ADVOGADO);
        public static final UniqueKey<TClasseProcessualRecord> CLASSE_PROCESSUAL_PK = createUniqueKey(TClasseProcessual.T_CLASSE_PROCESSUAL, TClasseProcessual.T_CLASSE_PROCESSUAL.SIG_CLASSE);
        public static final UniqueKey<TCompetenciaRecord> COMPETENCIA_PK = createUniqueKey(TCompetencia.T_COMPETENCIA, TCompetencia.T_COMPETENCIA.SIG_CLASSE, TCompetencia.T_COMPETENCIA.SIG_OJ);
        public static final UniqueKey<TComposicaoOjRecord> COMPOSICAO_PK = createUniqueKey(TComposicaoOj.T_COMPOSICAO_OJ, TComposicaoOj.T_COMPOSICAO_OJ.SIG_OJ, TComposicaoOj.T_COMPOSICAO_OJ.COD_MAGISTRADO);
        public static final UniqueKey<TDenParteFaseProcRecord> PK_T_DEN_PARTE_FASE_PROC = createUniqueKey(TDenParteFaseProc.T_DEN_PARTE_FASE_PROC, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.COD_PROCESSO, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.COD_PARTE, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.DTA_INICIO_FASE, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.SIG_CLASSE);
        public static final UniqueKey<TDistribuidorRecord> DISTRIBUIDOR_PK = createUniqueKey(TDistribuidor.T_DISTRIBUIDOR, TDistribuidor.T_DISTRIBUIDOR.COD_DISTRIBUIDOR);
        public static final UniqueKey<TFaseProcessualRecord> PK_T_FASE_PROCESSUAL = createUniqueKey(TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.COD_PROCESSO, TFaseProcessual.T_FASE_PROCESSUAL.DTA_INICIO_FASE, TFaseProcessual.T_FASE_PROCESSUAL.SIG_CLASSE);
        public static final UniqueKey<THistDistribuicaoRecord> HIST_DISTRIBUICAO_PK = createUniqueKey(THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.COD_DISTRIBUIDOR, THistDistribuicao.T_HIST_DISTRIBUICAO.SEQ_DISTRIBUICAO);
        public static final UniqueKey<TImpedimentoAdvogadoRecord> IMPEDIMENTO_ADVOGADO_PK = createUniqueKey(TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.COD_MAGISTRADO, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.NUM_ADVOGADO);
        public static final UniqueKey<TImpedimentoParteRecord> IMPEDIMENTO_PARTE_PK = createUniqueKey(TImpedimentoParte.T_IMPEDIMENTO_PARTE, TImpedimentoParte.T_IMPEDIMENTO_PARTE.COD_MAGISTRADO, TImpedimentoParte.T_IMPEDIMENTO_PARTE.COD_PARTE);
        public static final UniqueKey<TImpedimentoProcessoRecord> IMPEDIMENTO_PROCESSO_PK = createUniqueKey(TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_MAGISTRADO, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_PROCESSO);
        public static final UniqueKey<TMagistradoRecord> MAGISTRADO_PK = createUniqueKey(TMagistrado.T_MAGISTRADO, TMagistrado.T_MAGISTRADO.COD_MAGISTRADO);
        public static final UniqueKey<TMotivoRedistribuicaoRecord> MOTIVO_REDISTRIBUICAO_PK = createUniqueKey(TMotivoRedistribuicao.T_MOTIVO_REDISTRIBUICAO, TMotivoRedistribuicao.T_MOTIVO_REDISTRIBUICAO.COD_MOTIVO_REDIST);
        public static final UniqueKey<TOrgaoJudicanteRecord> ORGAO_JUDICANTE_PK = createUniqueKey(TOrgaoJudicante.T_ORGAO_JUDICANTE, TOrgaoJudicante.T_ORGAO_JUDICANTE.SIG_OJ);
        public static final UniqueKey<TParteRecord> PARTE_PK = createUniqueKey(TParte.T_PARTE, TParte.T_PARTE.COD_PARTE);
        public static final UniqueKey<TProcessoRecord> PROCESSO_PK = createUniqueKey(TProcesso.T_PROCESSO, TProcesso.T_PROCESSO.COD_PROCESSO);
        public static final UniqueKey<TProcessoParteRecord> PROCESSO_PARTE_PK = createUniqueKey(TProcessoParte.T_PROCESSO_PARTE, TProcessoParte.T_PROCESSO_PARTE.COD_PROCESSO, TProcessoParte.T_PROCESSO_PARTE.COD_PARTE);
        public static final UniqueKey<TProcessoParteAdvogadoRecord> PROCESSO_PARTE_ADVOGADO_PK = createUniqueKey(TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.COD_PROCESSO, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.COD_PARTE, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.NUM_ADVOGADO);
        public static final UniqueKey<TProcessoParteProcuradorRecord> PROCESSO_PARTE_PROCURADOR_PK = createUniqueKey(TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.COD_PROCESSO, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.COD_PARTE, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.NUM_PROCURADOR);
        public static final UniqueKey<TProcessoRelacionadoRecord> PROCESSO_RELACIONADO_PK = createUniqueKey(TProcessoRelacionado.T_PROCESSO_RELACIONADO, TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO, TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO_REL);
        public static final UniqueKey<TProcuradorRecord> PROCURADOR_PK = createUniqueKey(TProcurador.T_PROCURADOR, TProcurador.T_PROCURADOR.NUM_PROCURADOR);
        public static final UniqueKey<TProtocoloRecord> PK_T_PROTOCOLO = createUniqueKey(TProtocolo.T_PROTOCOLO, TProtocolo.T_PROTOCOLO.COD_PROTOCOLO);
        public static final UniqueKey<TTipoDistRecord> TIPO_DIST_PK = createUniqueKey(TTipoDist.T_TIPO_DIST, TTipoDist.T_TIPO_DIST.COD_TIPO_DIST);
        public static final UniqueKey<TTipoRelacionamentoRecord> TIPO_RELACIONAMENTO_PK = createUniqueKey(TTipoRelacionamento.T_TIPO_RELACIONAMENTO, TTipoRelacionamento.T_TIPO_RELACIONAMENTO.COD_TIPO_RELAC);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<TCompetenciaRecord, TClasseProcessualRecord> T_COMPETENCIA__COMPETENCIA_FK1 = createForeignKey(br.unb.sma.database.Keys.CLASSE_PROCESSUAL_PK, TCompetencia.T_COMPETENCIA, TCompetencia.T_COMPETENCIA.SIG_CLASSE);
        public static final ForeignKey<TCompetenciaRecord, TOrgaoJudicanteRecord> T_COMPETENCIA__COMPETENCIA_FK2 = createForeignKey(br.unb.sma.database.Keys.ORGAO_JUDICANTE_PK, TCompetencia.T_COMPETENCIA, TCompetencia.T_COMPETENCIA.SIG_OJ);
        public static final ForeignKey<TComposicaoOjRecord, TMagistradoRecord> T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK2 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, TComposicaoOj.T_COMPOSICAO_OJ, TComposicaoOj.T_COMPOSICAO_OJ.COD_MAGISTRADO);
        public static final ForeignKey<TComposicaoOjRecord, TOrgaoJudicanteRecord> T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK1 = createForeignKey(br.unb.sma.database.Keys.ORGAO_JUDICANTE_PK, TComposicaoOj.T_COMPOSICAO_OJ, TComposicaoOj.T_COMPOSICAO_OJ.SIG_OJ);
        public static final ForeignKey<TDenParteFaseProcRecord, TProcessoParteRecord> T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK1 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PARTE_PK, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.COD_PROCESSO, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.COD_PARTE);
        public static final ForeignKey<TDenParteFaseProcRecord, TFaseProcessualRecord> T_DEN_PARTE_FASE_PROC__DEN_PARTE_FASE_PROC_FK2 = createForeignKey(br.unb.sma.database.Keys.PK_T_FASE_PROCESSUAL, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.COD_PROCESSO, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.DTA_INICIO_FASE, TDenParteFaseProc.T_DEN_PARTE_FASE_PROC.SIG_CLASSE);
        public static final ForeignKey<TFaseProcessualRecord, TProcessoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK5 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.COD_PROCESSO);
        public static final ForeignKey<TFaseProcessualRecord, TClasseProcessualRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK1 = createForeignKey(br.unb.sma.database.Keys.CLASSE_PROCESSUAL_PK, TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.SIG_CLASSE);
        public static final ForeignKey<TFaseProcessualRecord, TMagistradoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK3 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.COD_MAGISTRADO);
        public static final ForeignKey<TFaseProcessualRecord, TMotivoRedistribuicaoRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK4 = createForeignKey(br.unb.sma.database.Keys.MOTIVO_REDISTRIBUICAO_PK, TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.COD_MOTIVO_REDIST);
        public static final ForeignKey<TFaseProcessualRecord, TOrgaoJudicanteRecord> T_FASE_PROCESSUAL__FASE_PROCESSUAL_FK2 = createForeignKey(br.unb.sma.database.Keys.ORGAO_JUDICANTE_PK, TFaseProcessual.T_FASE_PROCESSUAL, TFaseProcessual.T_FASE_PROCESSUAL.SIG_OJ);
        public static final ForeignKey<THistDistribuicaoRecord, TDistribuidorRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK1 = createForeignKey(br.unb.sma.database.Keys.DISTRIBUIDOR_PK, THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.COD_DISTRIBUIDOR);
        public static final ForeignKey<THistDistribuicaoRecord, TProcessoRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK3 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.COD_PROCESSO);
        public static final ForeignKey<THistDistribuicaoRecord, TTipoDistRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK2 = createForeignKey(br.unb.sma.database.Keys.TIPO_DIST_PK, THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.COD_TIPO_DIST);
        public static final ForeignKey<THistDistribuicaoRecord, TMagistradoRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK4 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.COD_MAGISTRADO);
        public static final ForeignKey<THistDistribuicaoRecord, TOrgaoJudicanteRecord> T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK5 = createForeignKey(br.unb.sma.database.Keys.ORGAO_JUDICANTE_PK, THistDistribuicao.T_HIST_DISTRIBUICAO, THistDistribuicao.T_HIST_DISTRIBUICAO.SIG_OJ);
        public static final ForeignKey<TImpedimentoAdvogadoRecord, TMagistradoRecord> T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK1 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.COD_MAGISTRADO);
        public static final ForeignKey<TImpedimentoAdvogadoRecord, TAdvogadoRecord> T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK2 = createForeignKey(br.unb.sma.database.Keys.ADVOGADO_PK, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO, TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO.NUM_ADVOGADO);
        public static final ForeignKey<TImpedimentoParteRecord, TMagistradoRecord> T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK1 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, TImpedimentoParte.T_IMPEDIMENTO_PARTE, TImpedimentoParte.T_IMPEDIMENTO_PARTE.COD_MAGISTRADO);
        public static final ForeignKey<TImpedimentoParteRecord, TParteRecord> T_IMPEDIMENTO_PARTE__IMPEDIMENTO_PARTE_FK2 = createForeignKey(br.unb.sma.database.Keys.PARTE_PK, TImpedimentoParte.T_IMPEDIMENTO_PARTE, TImpedimentoParte.T_IMPEDIMENTO_PARTE.COD_PARTE);
        public static final ForeignKey<TImpedimentoProcessoRecord, TMagistradoRecord> T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK1 = createForeignKey(br.unb.sma.database.Keys.MAGISTRADO_PK, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_MAGISTRADO);
        public static final ForeignKey<TImpedimentoProcessoRecord, TProcessoRecord> T_IMPEDIMENTO_PROCESSO__IMPEDIMENTO_PROCESSO_FK2 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO, TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO.COD_PROCESSO);
        public static final ForeignKey<TProcessoParteRecord, TProcessoRecord> T_PROCESSO_PARTE__PROCESSO_PARTE_FK1 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, TProcessoParte.T_PROCESSO_PARTE, TProcessoParte.T_PROCESSO_PARTE.COD_PROCESSO);
        public static final ForeignKey<TProcessoParteRecord, TParteRecord> T_PROCESSO_PARTE__PROCESSO_PARTE_FK2 = createForeignKey(br.unb.sma.database.Keys.PARTE_PK, TProcessoParte.T_PROCESSO_PARTE, TProcessoParte.T_PROCESSO_PARTE.COD_PARTE);
        public static final ForeignKey<TProcessoParteAdvogadoRecord, TProcessoParteRecord> T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK1 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PARTE_PK, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.COD_PROCESSO, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.COD_PARTE);
        public static final ForeignKey<TProcessoParteAdvogadoRecord, TAdvogadoRecord> T_PROCESSO_PARTE_ADVOGADO__PROCESSO_PARTE_ADVOGADO_FK2 = createForeignKey(br.unb.sma.database.Keys.ADVOGADO_PK, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO, TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO.NUM_ADVOGADO);
        public static final ForeignKey<TProcessoParteProcuradorRecord, TProcessoParteRecord> T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK1 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PARTE_PK, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.COD_PROCESSO, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.COD_PARTE);
        public static final ForeignKey<TProcessoParteProcuradorRecord, TProcuradorRecord> T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK2 = createForeignKey(br.unb.sma.database.Keys.PROCURADOR_PK, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR, TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR.NUM_PROCURADOR);
        public static final ForeignKey<TProcessoRelacionadoRecord, TProcessoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK1 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, TProcessoRelacionado.T_PROCESSO_RELACIONADO, TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO);
        public static final ForeignKey<TProcessoRelacionadoRecord, TProcessoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK2 = createForeignKey(br.unb.sma.database.Keys.PROCESSO_PK, TProcessoRelacionado.T_PROCESSO_RELACIONADO, TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_PROCESSO_REL);
        public static final ForeignKey<TProcessoRelacionadoRecord, TTipoRelacionamentoRecord> T_PROCESSO_RELACIONADO__PROCESSO_RELACIONAMENTO_FK3 = createForeignKey(br.unb.sma.database.Keys.TIPO_RELACIONAMENTO_PK, TProcessoRelacionado.T_PROCESSO_RELACIONADO, TProcessoRelacionado.T_PROCESSO_RELACIONADO.COD_TIPO_RELAC);
    }
}
