/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database;


import br.unb.sma.database.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in procjud
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * Advogados que atuam em Processos Judiciais
     */
    public static final TAdvogado T_ADVOGADO = br.unb.sma.database.tables.TAdvogado.T_ADVOGADO;

    /**
     * Classes Processuais classificam o processo judicial de acordo com o tipo de causa que se discute
     */
    public static final TClasseProcessual T_CLASSE_PROCESSUAL = br.unb.sma.database.tables.TClasseProcessual.T_CLASSE_PROCESSUAL;

    /**
     * Mapeamento entre as Classes Processuais e os Orgaos Judicantes para onde processos da classe podem ser distribuidos
     */
    public static final TCompetencia T_COMPETENCIA = br.unb.sma.database.tables.TCompetencia.T_COMPETENCIA;

    /**
     * Composicao dos Orgaos Judicantes: relaciona os magistrados com os OJs, indicando a data de inicio e termino da atuacao do Magistrados naquele OJ
     */
    public static final TComposicaoOj T_COMPOSICAO_OJ = br.unb.sma.database.tables.TComposicaoOj.T_COMPOSICAO_OJ;

    /**
     * Denominacao das partes do processo em uma determinada frase. Relaciona as tabela T_FASE_PROCESSUAL com T_PROCESSO_PARTE de forma a indicar qual a forma de atuacao da parte na fase processual determinada.
     */
    public static final TDenParteFaseProc T_DEN_PARTE_FASE_PROC = br.unb.sma.database.tables.TDenParteFaseProc.T_DEN_PARTE_FASE_PROC;

    /**
     * Responsavel pela realizacao de uma distribuicao de processo
     */
    public static final TDistribuidor T_DISTRIBUIDOR = br.unb.sma.database.tables.TDistribuidor.T_DISTRIBUIDOR;

    /**
     * Fases pelas quais passou um processo judicial. Um processo pode passar por varias fases. Para cada fase, pode ser atribuida uma classe processual diferente.
     */
    public static final TFaseProcessual T_FASE_PROCESSUAL = br.unb.sma.database.tables.TFaseProcessual.T_FASE_PROCESSUAL;

    /**
     * Historico de distribuicões realizadas
     */
    public static final THistDistribuicao T_HIST_DISTRIBUICAO = br.unb.sma.database.tables.THistDistribuicao.T_HIST_DISTRIBUICAO;

    /**
     * Impedimento de Magistrados em relacao a Advogados que atuam em processos
     */
    public static final TImpedimentoAdvogado T_IMPEDIMENTO_ADVOGADO = br.unb.sma.database.tables.TImpedimentoAdvogado.T_IMPEDIMENTO_ADVOGADO;

    /**
     * Impedimento de Magistrados em relacao as Partes de processos
     */
    public static final TImpedimentoParte T_IMPEDIMENTO_PARTE = br.unb.sma.database.tables.TImpedimentoParte.T_IMPEDIMENTO_PARTE;

    /**
     * Impedimento de Magistrados em relacao a Processos especificos
     */
    public static final TImpedimentoProcesso T_IMPEDIMENTO_PROCESSO = br.unb.sma.database.tables.TImpedimentoProcesso.T_IMPEDIMENTO_PROCESSO;

    /**
     * informações com detalhes acerca de distribuições realizadas
     */
    public static final TInfoDistribuicao T_INFO_DISTRIBUICAO = br.unb.sma.database.tables.TInfoDistribuicao.T_INFO_DISTRIBUICAO;

    /**
     * Magistrados que atuam em Orgaos Judicantes para julgar processos
     */
    public static final TMagistrado T_MAGISTRADO = br.unb.sma.database.tables.TMagistrado.T_MAGISTRADO;

    /**
     * Relaciona os possiveis motivos para redistribuicao de um processo
     */
    public static final TMotivoRedistribuicao T_MOTIVO_REDISTRIBUICAO = br.unb.sma.database.tables.TMotivoRedistribuicao.T_MOTIVO_REDISTRIBUICAO;

    /**
     * Entidade diretamente responsavel por conduzir e decidir um determinado processo judicial
     */
    public static final TOrgaoJudicante T_ORGAO_JUDICANTE = br.unb.sma.database.tables.TOrgaoJudicante.T_ORGAO_JUDICANTE;

    /**
     * Partes do Processo Judicial
     */
    public static final TParte T_PARTE = br.unb.sma.database.tables.TParte.T_PARTE;

    /**
     * Processos Judiciais Autuados. Os processos possuem uma identificacao interna COD_PROCESSO utilizada no banco de dados e uma identificacao padrao (numeracao unica) utilizada em todos os ramos do Poder Judiciario. A identificacao padrao e utilizada desde jan/2010 no TST e possui o formato numerico de 20 digitos NNNNNNN-DD.AAAA.J.TR.OOOO
     */
    public static final TProcesso T_PROCESSO = br.unb.sma.database.tables.TProcesso.T_PROCESSO;

    /**
     * Relaciona as Partes interessadas em Processos Judiciais
     */
    public static final TProcessoParte T_PROCESSO_PARTE = br.unb.sma.database.tables.TProcessoParte.T_PROCESSO_PARTE;

    /**
     * Relaciona os Advogados das Partes interessadas em Processos Judiciais
     */
    public static final TProcessoParteAdvogado T_PROCESSO_PARTE_ADVOGADO = br.unb.sma.database.tables.TProcessoParteAdvogado.T_PROCESSO_PARTE_ADVOGADO;

    /**
     * Relaciona os Procuradores das Partes interessadas em Processos Judiciais
     */
    public static final TProcessoParteProcurador T_PROCESSO_PARTE_PROCURADOR = br.unb.sma.database.tables.TProcessoParteProcurador.T_PROCESSO_PARTE_PROCURADOR;

    /**
     * Identifica conexao entre Processos de forma a permitir a Distribuicao por dependência
     */
    public static final TProcessoRelacionado T_PROCESSO_RELACIONADO = br.unb.sma.database.tables.TProcessoRelacionado.T_PROCESSO_RELACIONADO;

    /**
     * Procuradores que atuam em Processos Judiciais
     */
    public static final TProcurador T_PROCURADOR = br.unb.sma.database.tables.TProcurador.T_PROCURADOR;

    /**
     * Unidades de protocolo
     */
    public static final TProtocolo T_PROTOCOLO = br.unb.sma.database.tables.TProtocolo.T_PROTOCOLO;

    /**
     * Tipos de Distribuicao
     */
    public static final TTipoDist T_TIPO_DIST = br.unb.sma.database.tables.TTipoDist.T_TIPO_DIST;

    /**
     * Ttipos de relacionamento entre dois processos
     */
    public static final TTipoRelacionamento T_TIPO_RELACIONAMENTO = br.unb.sma.database.tables.TTipoRelacionamento.T_TIPO_RELACIONAMENTO;
}
