Insert into PROCJUD.T_TIPO_RELACIONAMENTO
   (COD_TIPO_RELAC, DES_TIPO_RELAC)
 Values
   (1, 'Prevenção');
Insert into PROCJUD.T_TIPO_RELACIONAMENTO
   (COD_TIPO_RELAC, DES_TIPO_RELAC)
 Values
   (2, 'Dependência');
Insert into PROCJUD.T_TIPO_RELACIONAMENTO
   (COD_TIPO_RELAC, DES_TIPO_RELAC)
 Values
   (3, 'Referência');
Insert into PROCJUD.T_TIPO_RELACIONAMENTO
   (COD_TIPO_RELAC, DES_TIPO_RELAC)
 Values
   (4, 'Origem AIRE');
COMMIT;
