Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (74, 'MRLP', TO_DATE('04/15/2002 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MRLP', TO_DATE('04/15/2002 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MVMF', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MLBC', TO_DATE('07/28/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MACV', TO_DATE('12/28/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MALB', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (516, 'MACV', TO_DATE('03/03/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (79, 'MALB', TO_DATE('03/03/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (364, 'MABL', TO_DATE('03/07/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MIGM', TO_DATE('12/12/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (518, 'MDMC', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MMGD', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MWOC', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (69, 'MWOC', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MFEO', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MMGD', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MMEA', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (518, 'MMEA', TO_DATE('11/14/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MDMA', TO_DATE('03/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MMCP', TO_DATE('03/02/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MRLP', TO_DATE('03/07/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (79, 'MMGD', TO_DATE('03/20/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (69, 'MHCS', TO_DATE('07/16/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (79, 'MAAB', TO_DATE('07/16/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MMAC', TO_DATE('07/16/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (89, 'MCB', TO_DATE('09/25/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (517, 'MVMF', TO_DATE('03/06/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MJD', TO_DATE('03/06/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MJD', TO_DATE('03/06/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MMGD', TO_DATE('03/15/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MACC', TO_DATE('03/15/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MDMA', TO_DATE('03/15/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MHCS', TO_DATE('03/15/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MALB', TO_DATE('04/19/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MAAB', TO_DATE('04/19/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MDMC', TO_DATE('03/18/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MMEA', TO_DATE('03/18/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MDAR', TO_DATE('04/23/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (517, 'MDAR', TO_DATE('04/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MMHM', TO_DATE('12/23/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (89, 'MMHM', TO_DATE('12/23/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (518, 'MMCP', TO_DATE('04/30/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MMCP', TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MWOC', TO_DATE('06/17/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MFEO', TO_DATE('10/04/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MCB', TO_DATE('10/04/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MRLP', TO_DATE('06/28/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (516, 'MKA', TO_DATE('04/23/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MWOC', TO_DATE('08/13/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MJD', TO_DATE('03/02/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MAAB', TO_DATE('07/16/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MHCS', TO_DATE('07/16/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (84, 'MJD', TO_DATE('03/06/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MCB', TO_DATE('03/11/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MHCS', TO_DATE('04/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MDMA', TO_DATE('04/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (74, 'MDMA', TO_DATE('04/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MDAR', TO_DATE('04/22/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MVMF', TO_DATE('01/07/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MCMB', TO_DATE('01/07/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MKA', TO_DATE('03/13/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MACC', TO_DATE('12/14/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MJRP', TO_DATE('09/03/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MJRP', TO_DATE('09/03/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (74, 'MJRP', TO_DATE('09/03/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (517, 'MCMB', TO_DATE('07/11/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MCMB', TO_DATE('07/11/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (47, 'MKA', TO_DATE('03/27/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MKA', TO_DATE('03/27/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MCB', TO_DATE('02/06/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (58, 'MEMP', TO_DATE('06/05/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MEMP', TO_DATE('06/05/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (41, 'MEMP', TO_DATE('06/05/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (89, 'MEMP', TO_DATE('06/05/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MBP', TO_DATE('05/31/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MACV', TO_DATE('12/28/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (84, 'MMAC', TO_DATE('05/17/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MDMC', TO_DATE('05/17/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (360, 'MMAC', TO_DATE('05/17/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (53, 'MACC', TO_DATE('12/14/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
Insert into PROCJUD.T_COMPOSICAO_OJ
   (COD_OJ, COD_MAGISTRADO, DTA_INI_ATUACAO, DTA_TER_ATUACAO, IND_PRESIDENTE)
 Values
   (516, 'MACC', TO_DATE('12/14/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'false');
COMMIT;
