/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TAdvogadoRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Advogados que atuam em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TAdvogado extends TableImpl<TAdvogadoRecord> {

    /**
     * The reference instance of <code>procjud.t_advogado</code>
     */
    public static final TAdvogado T_ADVOGADO = new TAdvogado();
    private static final long serialVersionUID = 1428391237;
    /**
     * The column <code>procjud.t_advogado.num_advogado</code>. Numero de identificacao do Advogado
     */
    public final TableField<TAdvogadoRecord, Integer> NUM_ADVOGADO = createField("num_advogado", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numero de identificacao do Advogado");
    /**
     * The column <code>procjud.t_advogado.nom_advogado</code>. Nome Completo do Advogado
     */
    public final TableField<TAdvogadoRecord, String> NOM_ADVOGADO = createField("nom_advogado", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "Nome Completo do Advogado");
    /**
     * The column <code>procjud.t_advogado.num_oab</code>. Numero de inscricao do advogado na OAB
     */
    public final TableField<TAdvogadoRecord, Integer> NUM_OAB = createField("num_oab", org.jooq.impl.SQLDataType.INTEGER, this, "Numero de inscricao do advogado na OAB");
    /**
     * The column <code>procjud.t_advogado.sig_uf_oab</code>. Sigla da UF da OAB onde o Advogado esta registrado
     */
    public final TableField<TAdvogadoRecord, String> SIG_UF_OAB = createField("sig_uf_oab", org.jooq.impl.SQLDataType.CHAR.length(2), this, "Sigla da UF da OAB onde o Advogado esta registrado");

    /**
     * Create a <code>procjud.t_advogado</code> table reference
     */
    public TAdvogado() {
        this("t_advogado", null);
    }

    /**
     * Create an aliased <code>procjud.t_advogado</code> table reference
     */
    public TAdvogado(String alias) {
        this(alias, T_ADVOGADO);
    }

    private TAdvogado(String alias, Table<TAdvogadoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TAdvogado(String alias, Table<TAdvogadoRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "Advogados que atuam em Processos Judiciais");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAdvogadoRecord> getRecordType() {
        return TAdvogadoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAdvogadoRecord> getPrimaryKey() {
        return Keys.ADVOGADO_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAdvogadoRecord>> getKeys() {
        return Arrays.<UniqueKey<TAdvogadoRecord>>asList(Keys.ADVOGADO_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAdvogado as(String alias) {
        return new TAdvogado(alias, this);
    }

    /**
     * Rename this table
     */
    public TAdvogado rename(String name) {
        return new TAdvogado(name, null);
    }
}
