/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TClasseProcessualRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Classes Processuais classificam o processo judicial de acordo com o tipo 
 * de causa que se discute
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TClasseProcessual extends TableImpl<TClasseProcessualRecord> {

	/**
	 * The reference instance of <code>procjud.t_classe_processual</code>
	 */
	public static final TClasseProcessual T_CLASSE_PROCESSUAL = new TClasseProcessual();
	private static final long serialVersionUID = 1731407425;
	/**
	 * The column <code>procjud.t_classe_processual.sig_classe</code>. Sigla identificadora da classe
	 */
	public final TableField<TClasseProcessualRecord, String> SIG_CLASSE = createField("sig_classe", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "Sigla identificadora da classe");
	/**
	 * The column <code>procjud.t_classe_processual.nom_classe</code>. Nome completo da classe
	 */
	public final TableField<TClasseProcessualRecord, String> NOM_CLASSE = createField("nom_classe", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "Nome completo da classe");
	/**
	 * The column <code>procjud.t_classe_processual.num_classe_cnj</code>. Numeracao da classe segundo classificacao do CNJ
	 */
	public final TableField<TClasseProcessualRecord, Integer> NUM_CLASSE_CNJ = createField("num_classe_cnj", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numeracao da classe segundo classificacao do CNJ");
	/**
	 * The column <code>procjud.t_classe_processual.nom_polo_ativo</code>. Designacao dada ao polo ativo da causa (o autor)
	 */
	public final TableField<TClasseProcessualRecord, String> NOM_POLO_ATIVO = createField("nom_polo_ativo", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "Designacao dada ao polo ativo da causa (o autor)");
	/**
	 * The column <code>procjud.t_classe_processual.nom_polo_passivo</code>. Designacao dada ao polo passivo da causa (o reu)
	 */
	public final TableField<TClasseProcessualRecord, String> NOM_POLO_PASSIVO = createField("nom_polo_passivo", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "Designacao dada ao polo passivo da causa (o reu)");
	/**
	 * The column <code>procjud.t_classe_processual.ind_fase_inicial</code>. Indica se a classe e atribuida na fase inicial do processo, ou diz respeito a fases de recursos
	 */
	public final TableField<TClasseProcessualRecord, Boolean> IND_FASE_INICIAL = createField("ind_fase_inicial", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "Indica se a classe e atribuida na fase inicial do processo, ou diz respeito a fases de recursos");

	/**
	 * Create a <code>procjud.t_classe_processual</code> table reference
	 */
	public TClasseProcessual() {
		this("t_classe_processual", null);
	}

	/**
	 * Create an aliased <code>procjud.t_classe_processual</code> table reference
	 */
	public TClasseProcessual(String alias) {
		this(alias, T_CLASSE_PROCESSUAL);
	}

	private TClasseProcessual(String alias, Table<TClasseProcessualRecord> aliased) {
		this(alias, aliased, null);
	}

	private TClasseProcessual(String alias, Table<TClasseProcessualRecord> aliased, Field<?>[] parameters) {
		super(alias, Procjud.PROCJUD, aliased, parameters, "Classes Processuais classificam o processo judicial de acordo com o tipo de causa que se discute");
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TClasseProcessualRecord> getRecordType() {
		return TClasseProcessualRecord.class;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TClasseProcessualRecord> getPrimaryKey() {
		return Keys.CLASSE_PROCESSUAL_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TClasseProcessualRecord>> getKeys() {
		return Arrays.<UniqueKey<TClasseProcessualRecord>>asList(Keys.CLASSE_PROCESSUAL_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TClasseProcessual as(String alias) {
		return new TClasseProcessual(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TClasseProcessual rename(String name) {
		return new TClasseProcessual(name, null);
	}
}
