/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TComposicaoOjRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * Composicao dos Orgaos Judicantes: relaciona os magistrados com os OJs, 
 * indicando a data de inicio e termino da atuacao do Magistrados naquele 
 * OJ
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TComposicaoOj extends TableImpl<TComposicaoOjRecord> {

	/**
	 * The reference instance of <code>procjud.t_composicao_oj</code>
	 */
	public static final TComposicaoOj T_COMPOSICAO_OJ = new TComposicaoOj();
	private static final long serialVersionUID = -159097545;
	/**
	 * The column <code>procjud.t_composicao_oj.cod_magistrado</code>. Codigo Identificador do Magistrado
	 */
	public final TableField<TComposicaoOjRecord, String> COD_MAGISTRADO = createField("cod_magistrado", org.jooq.impl.SQLDataType.VARCHAR.length(4).nullable(false), this, "Codigo Identificador do Magistrado");
	/**
	 * The column <code>procjud.t_composicao_oj.dta_ini_atuacao</code>. Data de inicio da atuacao do Magistrado no OJ
	 */
	public final TableField<TComposicaoOjRecord, Date> DTA_INI_ATUACAO = createField("dta_ini_atuacao", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "Data de inicio da atuacao do Magistrado no OJ");
	/**
	 * The column <code>procjud.t_composicao_oj.dta_ter_atuacao</code>. Data de termino da atuacao do Magistrado no OJ
	 */
	public final TableField<TComposicaoOjRecord, Date> DTA_TER_ATUACAO = createField("dta_ter_atuacao", org.jooq.impl.SQLDataType.DATE, this, "Data de termino da atuacao do Magistrado no OJ");
	/**
	 * The column <code>procjud.t_composicao_oj.ind_presidente</code>. Indica se o magistrado e o presidente do respectivo OJ
	 */
	public final TableField<TComposicaoOjRecord, Boolean> IND_PRESIDENTE = createField("ind_presidente", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "Indica se o magistrado e o presidente do respectivo OJ");
	/**
	 * The column <code>procjud.t_composicao_oj.sig_oj</code>. sigla do orgao judicante
	 */
	public final TableField<TComposicaoOjRecord, String> SIG_OJ = createField("sig_oj", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "sigla do orgao judicante");

	/**
	 * Create a <code>procjud.t_composicao_oj</code> table reference
	 */
	public TComposicaoOj() {
		this("t_composicao_oj", null);
	}

	/**
	 * Create an aliased <code>procjud.t_composicao_oj</code> table reference
	 */
	public TComposicaoOj(String alias) {
		this(alias, T_COMPOSICAO_OJ);
	}

	private TComposicaoOj(String alias, Table<TComposicaoOjRecord> aliased) {
		this(alias, aliased, null);
	}

	private TComposicaoOj(String alias, Table<TComposicaoOjRecord> aliased, Field<?>[] parameters) {
		super(alias, Procjud.PROCJUD, aliased, parameters, "Composicao dos Orgaos Judicantes: relaciona os magistrados com os OJs, indicando a data de inicio e termino da atuacao do Magistrados naquele OJ");
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TComposicaoOjRecord> getRecordType() {
		return TComposicaoOjRecord.class;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TComposicaoOjRecord> getPrimaryKey() {
		return Keys.COMPOSICAO_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TComposicaoOjRecord>> getKeys() {
		return Arrays.<UniqueKey<TComposicaoOjRecord>>asList(Keys.COMPOSICAO_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TComposicaoOjRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TComposicaoOjRecord, ?>>asList(Keys.T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK2, Keys.T_COMPOSICAO_OJ__COMPOSICAO_OJ_FK1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TComposicaoOj as(String alias) {
		return new TComposicaoOj(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TComposicaoOj rename(String name) {
		return new TComposicaoOj(name, null);
	}
}
