/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.THistDistribuicaoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * Historico de distribuicões realizadas
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class THistDistribuicao extends TableImpl<THistDistribuicaoRecord> {

    /**
     * The reference instance of <code>procjud.t_hist_distribuicao</code>
     */
    public static final THistDistribuicao T_HIST_DISTRIBUICAO = new THistDistribuicao();
    private static final long serialVersionUID = -717589651;
    /**
     * The column <code>procjud.t_hist_distribuicao.cod_distribuidor</code>. Codigo que identifica o distribuidor do processo
     */
    public final TableField<THistDistribuicaoRecord, String> COD_DISTRIBUIDOR = createField("cod_distribuidor", org.jooq.impl.SQLDataType.CHAR.length(8).nullable(false), this, "Codigo que identifica o distribuidor do processo");
    /**
     * The column <code>procjud.t_hist_distribuicao.seq_distribuicao</code>. Numero sequencial da distribuicao de acordo com o Distribuidor
     */
    public final TableField<THistDistribuicaoRecord, Integer> SEQ_DISTRIBUICAO = createField("seq_distribuicao", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numero sequencial da distribuicao de acordo com o Distribuidor");
    /**
     * The column <code>procjud.t_hist_distribuicao.cod_processo</code>. Codigo numerico do processo distribuido
     */
    public final TableField<THistDistribuicaoRecord, Long> COD_PROCESSO = createField("cod_processo", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Codigo numerico do processo distribuido");
    /**
     * The column <code>procjud.t_hist_distribuicao.cod_tipo_dist</code>. Codigo do tipo de distribuicao
     */
    public final TableField<THistDistribuicaoRecord, String> COD_TIPO_DIST = createField("cod_tipo_dist", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "Codigo do tipo de distribuicao");
    /**
     * The column <code>procjud.t_hist_distribuicao.dta_distribuicao</code>. Data de realizacao da distribuicao do processo
     */
    public final TableField<THistDistribuicaoRecord, Date> DTA_DISTRIBUICAO = createField("dta_distribuicao", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "Data de realizacao da distribuicao do processo");
    /**
     * The column <code>procjud.t_hist_distribuicao.cod_magistrado</code>. Codigo Identificador do Magistrado para qual o processo foi distribuido
     */
    public final TableField<THistDistribuicaoRecord, String> COD_MAGISTRADO = createField("cod_magistrado", org.jooq.impl.SQLDataType.VARCHAR.length(4).nullable(false), this, "Codigo Identificador do Magistrado para qual o processo foi distribuido");
    /**
     * The column <code>procjud.t_hist_distribuicao.txt_distribuicao</code>. Registra detalhes da distribuicao para fins de posterior analise
     */
    public final TableField<THistDistribuicaoRecord, String> TXT_DISTRIBUICAO = createField("txt_distribuicao", org.jooq.impl.SQLDataType.VARCHAR.length(2048).nullable(false), this, "Registra detalhes da distribuicao para fins de posterior analise");
    /**
     * The column <code>procjud.t_hist_distribuicao.sig_oj</code>.
     */
    public final TableField<THistDistribuicaoRecord, String> SIG_OJ = createField("sig_oj", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

    /**
     * Create a <code>procjud.t_hist_distribuicao</code> table reference
     */
    public THistDistribuicao() {
        this("t_hist_distribuicao", null);
    }

    /**
     * Create an aliased <code>procjud.t_hist_distribuicao</code> table reference
     */
    public THistDistribuicao(String alias) {
        this(alias, T_HIST_DISTRIBUICAO);
    }

    private THistDistribuicao(String alias, Table<THistDistribuicaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private THistDistribuicao(String alias, Table<THistDistribuicaoRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "Historico de distribuicões realizadas");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<THistDistribuicaoRecord> getRecordType() {
        return THistDistribuicaoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<THistDistribuicaoRecord> getPrimaryKey() {
        return Keys.HIST_DISTRIBUICAO_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<THistDistribuicaoRecord>> getKeys() {
        return Arrays.<UniqueKey<THistDistribuicaoRecord>>asList(Keys.HIST_DISTRIBUICAO_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<THistDistribuicaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<THistDistribuicaoRecord, ?>>asList(Keys.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK1, Keys.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK3, Keys.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK2, Keys.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK4, Keys.T_HIST_DISTRIBUICAO__HIST_DISTRIBUICAO_FK5);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THistDistribuicao as(String alias) {
        return new THistDistribuicao(alias, this);
    }

    /**
     * Rename this table
     */
    public THistDistribuicao rename(String name) {
        return new THistDistribuicao(name, null);
    }
}
