/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TImpedimentoAdvogadoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * Impedimento de Magistrados em relacao a Advogados que atuam em processos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TImpedimentoAdvogado extends TableImpl<TImpedimentoAdvogadoRecord> {

    /**
     * The reference instance of <code>procjud.t_impedimento_advogado</code>
     */
    public static final TImpedimentoAdvogado T_IMPEDIMENTO_ADVOGADO = new TImpedimentoAdvogado();
    private static final long serialVersionUID = 283027542;
    /**
     * The column <code>procjud.t_impedimento_advogado.cod_magistrado</code>. Codigo Identificador do Magistrado
     */
    public final TableField<TImpedimentoAdvogadoRecord, String> COD_MAGISTRADO = createField("cod_magistrado", org.jooq.impl.SQLDataType.VARCHAR.length(4).nullable(false), this, "Codigo Identificador do Magistrado");
    /**
     * The column <code>procjud.t_impedimento_advogado.num_advogado</code>. Numero de identificacao do Advogado
     */
    public final TableField<TImpedimentoAdvogadoRecord, Integer> NUM_ADVOGADO = createField("num_advogado", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numero de identificacao do Advogado");
    /**
     * The column <code>procjud.t_impedimento_advogado.dta_registro</code>. Data de registro do impedimento
     */
    public final TableField<TImpedimentoAdvogadoRecord, Date> DTA_REGISTRO = createField("dta_registro", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "Data de registro do impedimento");

    /**
     * Create a <code>procjud.t_impedimento_advogado</code> table reference
     */
    public TImpedimentoAdvogado() {
        this("t_impedimento_advogado", null);
    }

    /**
     * Create an aliased <code>procjud.t_impedimento_advogado</code> table reference
     */
    public TImpedimentoAdvogado(String alias) {
        this(alias, T_IMPEDIMENTO_ADVOGADO);
    }

    private TImpedimentoAdvogado(String alias, Table<TImpedimentoAdvogadoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TImpedimentoAdvogado(String alias, Table<TImpedimentoAdvogadoRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "Impedimento de Magistrados em relacao a Advogados que atuam em processos");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TImpedimentoAdvogadoRecord> getRecordType() {
        return TImpedimentoAdvogadoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TImpedimentoAdvogadoRecord> getPrimaryKey() {
        return Keys.IMPEDIMENTO_ADVOGADO_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TImpedimentoAdvogadoRecord>> getKeys() {
        return Arrays.<UniqueKey<TImpedimentoAdvogadoRecord>>asList(Keys.IMPEDIMENTO_ADVOGADO_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TImpedimentoAdvogadoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TImpedimentoAdvogadoRecord, ?>>asList(Keys.T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK1, Keys.T_IMPEDIMENTO_ADVOGADO__IMPEDIMENTO_ADVOGADO_FK2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TImpedimentoAdvogado as(String alias) {
        return new TImpedimentoAdvogado(alias, this);
    }

    /**
     * Rename this table
     */
    public TImpedimentoAdvogado rename(String name) {
        return new TImpedimentoAdvogado(name, null);
    }
}
