/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TInfoDistribuicaoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * informações com detalhes acerca de distribuições realizadas
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TInfoDistribuicao extends TableImpl<TInfoDistribuicaoRecord> {

    /**
     * The reference instance of <code>procjud.t_info_distribuicao</code>
     */
    public static final TInfoDistribuicao T_INFO_DISTRIBUICAO = new TInfoDistribuicao();
    private static final long serialVersionUID = 2123147164;
    /**
     * The column <code>procjud.t_info_distribuicao.seq_informacao</code>. identificador único da informação
     */
    public final TableField<TInfoDistribuicaoRecord, Integer> SEQ_INFORMACAO = createField("seq_informacao", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "identificador único da informação");
    /**
     * The column <code>procjud.t_info_distribuicao.dta_informacao</code>. data de registro da informação
     */
    public final TableField<TInfoDistribuicaoRecord, Timestamp> DTA_INFORMACAO = createField("dta_informacao", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "data de registro da informação");
    /**
     * The column <code>procjud.t_info_distribuicao.cod_agente</code>. código do agente responsável pela informação
     */
    public final TableField<TInfoDistribuicaoRecord, String> COD_AGENTE = createField("cod_agente", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "código do agente responsável pela informação");
    /**
     * The column <code>procjud.t_info_distribuicao.tip_informacao</code>. tipo de informação registrada
     */
    public final TableField<TInfoDistribuicaoRecord, String> TIP_INFORMACAO = createField("tip_informacao", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "tipo de informação registrada");
    /**
     * The column <code>procjud.t_info_distribuicao.seq_distribuicao</code>. número sequencial da distribuição (se houver) relativa a informação provida
     */
    public final TableField<TInfoDistribuicaoRecord, Integer> SEQ_DISTRIBUICAO = createField("seq_distribuicao", org.jooq.impl.SQLDataType.INTEGER, this, "número sequencial da distribuição (se houver) relativa a informação provida");
    /**
     * The column <code>procjud.t_info_distribuicao.txt_informacao</code>. texto da informação
     */
    public final TableField<TInfoDistribuicaoRecord, String> TXT_INFORMACAO = createField("txt_informacao", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "texto da informação");
    /**
     * The column <code>procjud.t_info_distribuicao.txt_detalhes</code>. detalhes adicionais da informação, preenchido se necessário de acordo com o tipo de informação
     */
    public final TableField<TInfoDistribuicaoRecord, String> TXT_DETALHES = createField("txt_detalhes", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "detalhes adicionais da informação, preenchido se necessário de acordo com o tipo de informação");

    /**
     * Create a <code>procjud.t_info_distribuicao</code> table reference
     */
    public TInfoDistribuicao() {
        this("t_info_distribuicao", null);
    }

    /**
     * Create an aliased <code>procjud.t_info_distribuicao</code> table reference
     */
    public TInfoDistribuicao(String alias) {
        this(alias, T_INFO_DISTRIBUICAO);
    }

    private TInfoDistribuicao(String alias, Table<TInfoDistribuicaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TInfoDistribuicao(String alias, Table<TInfoDistribuicaoRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "informações com detalhes acerca de distribuições realizadas");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TInfoDistribuicaoRecord> getRecordType() {
        return TInfoDistribuicaoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TInfoDistribuicaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_INFO_DISTRIBUICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TInfoDistribuicaoRecord> getPrimaryKey() {
        return Keys.T_INFO_DISTRIBUICAO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TInfoDistribuicaoRecord>> getKeys() {
        return Arrays.<UniqueKey<TInfoDistribuicaoRecord>>asList(Keys.T_INFO_DISTRIBUICAO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TInfoDistribuicao as(String alias) {
        return new TInfoDistribuicao(alias, this);
    }

    /**
     * Rename this table
     */
    public TInfoDistribuicao rename(String name) {
        return new TInfoDistribuicao(name, null);
    }
}
