/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TProcessoRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * Processos Judiciais Autuados. Os processos possuem uma identificacao interna
 * COD_PROCESSO utilizada no banco de dados e uma identificacao padrao (numeracao
 * unica) utilizada em todos os ramos do Poder Judiciario. A identificacao
 * padrao e utilizada desde jan/2010 no TST e possui o formato numerico de
 * 20 digitos NNNNNNN-DD.AAAA.J.TR.OOOO
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcesso extends TableImpl<TProcessoRecord> {

    /**
     * The reference instance of <code>procjud.t_processo</code>
     */
    public static final TProcesso T_PROCESSO = new TProcesso();
    private static final long serialVersionUID = -1153371893;
    /**
     * The column <code>procjud.t_processo.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public final TableField<TProcessoRecord, Long> COD_PROCESSO = createField("cod_processo", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Codigo numerico atribuido ao processo para identifica-lo no banco de dados");
    /**
     * The column <code>procjud.t_processo.num_processo</code>. NNNNNNN -  numero de ordem de autuacao do processo, no ano de autuacao e na unidade jurisdicional de origem
     */
    public final TableField<TProcessoRecord, Integer> NUM_PROCESSO = createField("num_processo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "NNNNNNN -  numero de ordem de autuacao do processo, no ano de autuacao e na unidade jurisdicional de origem");
    /**
     * The column <code>procjud.t_processo.num_digito</code>. DD - digitos verificadores da integridade do numero do processo.
     */
    public final TableField<TProcessoRecord, Byte> NUM_DIGITO = createField("num_digito", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "DD - digitos verificadores da integridade do numero do processo.");
    /**
     * The column <code>procjud.t_processo.ano_processo</code>. AAAA - ano da ajuizamento do processo
     */
    public final TableField<TProcessoRecord, Short> ANO_PROCESSO = createField("ano_processo", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "AAAA - ano da ajuizamento do processo");
    /**
     * The column <code>procjud.t_processo.num_segmento</code>. J - digito identificador do segmento do Judiciario a que pertence o processo. 1 - STF, 2 - CNJ, 3 - STJ, 4 - JF, 5 - JT, 6 - JE, 7 - JM da Uniao, 8 - Justica dos Estados e do DF, 9 JM Estadual
     */
    public final TableField<TProcessoRecord, Byte> NUM_SEGMENTO = createField("num_segmento", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "J - digito identificador do segmento do Judiciario a que pertence o processo. 1 - STF, 2 - CNJ, 3 - STJ, 4 - JF, 5 - JT, 6 - JE, 7 - JM da Uniao, 8 - Justica dos Estados e do DF, 9 JM Estadual");
    /**
     * The column <code>procjud.t_processo.num_tribunal</code>. TR - tribunal ou conselho do segmento do Poder Judiciario a que pertence o processo; para os tribunais superiores (STF, STJ, TST, TSE e STM) e o CNJ, o codigo devera ser preenchido com zero (00), para os Conselhos da Justica Federal e Superior da Justica do Trabalho, devera ser preenchido com o numero 90 (noventa), para os demais tribunais, com um numero identificador do tribunal
     */
    public final TableField<TProcessoRecord, Byte> NUM_TRIBUNAL = createField("num_tribunal", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "TR - tribunal ou conselho do segmento do Poder Judiciario a que pertence o processo; para os tribunais superiores (STF, STJ, TST, TSE e STM) e o CNJ, o codigo devera ser preenchido com zero (00), para os Conselhos da Justica Federal e Superior da Justica do Trabalho, devera ser preenchido com o numero 90 (noventa), para os demais tribunais, com um numero identificador do tribunal");
    /**
     * The column <code>procjud.t_processo.num_origem</code>. OOOO - unidade de origem do processo, seguindo regras diversas para cada um dos segmentos do Judiciario, a excecao dos tribunais e conselhos, que terao esses digitos preenchidos com zero (0000)
     */
    public final TableField<TProcessoRecord, Short> NUM_ORIGEM = createField("num_origem", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "OOOO - unidade de origem do processo, seguindo regras diversas para cada um dos segmentos do Judiciario, a excecao dos tribunais e conselhos, que terao esses digitos preenchidos com zero (0000)");
    /**
     * The column <code>procjud.t_processo.dta_autuacao</code>. Data de autuacao do processo
     */
    public final TableField<TProcessoRecord, Date> DTA_AUTUACAO = createField("dta_autuacao", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "Data de autuacao do processo");

    /**
     * Create a <code>procjud.t_processo</code> table reference
     */
    public TProcesso() {
        this("t_processo", null);
    }

    /**
     * Create an aliased <code>procjud.t_processo</code> table reference
     */
    public TProcesso(String alias) {
        this(alias, T_PROCESSO);
    }

    private TProcesso(String alias, Table<TProcessoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TProcesso(String alias, Table<TProcessoRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "Processos Judiciais Autuados. Os processos possuem uma identificacao interna COD_PROCESSO utilizada no banco de dados e uma identificacao padrao (numeracao unica) utilizada em todos os ramos do Poder Judiciario. A identificacao padrao e utilizada desde jan/2010 no TST e possui o formato numerico de 20 digitos NNNNNNN-DD.AAAA.J.TR.OOOO");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProcessoRecord> getRecordType() {
        return TProcessoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TProcessoRecord> getPrimaryKey() {
        return Keys.PROCESSO_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TProcessoRecord>> getKeys() {
        return Arrays.<UniqueKey<TProcessoRecord>>asList(Keys.PROCESSO_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcesso as(String alias) {
        return new TProcesso(alias, this);
    }

    /**
     * Rename this table
     */
    public TProcesso rename(String name) {
        return new TProcesso(name, null);
    }
}
