/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TProcessoParteProcuradorRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Relaciona os Procuradores das Partes interessadas em Processos Judiciais
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcessoParteProcurador extends TableImpl<TProcessoParteProcuradorRecord> {

    /**
     * The reference instance of <code>procjud.t_processo_parte_procurador</code>
     */
    public static final TProcessoParteProcurador T_PROCESSO_PARTE_PROCURADOR = new TProcessoParteProcurador();
    private static final long serialVersionUID = -1440125278;
    /**
     * The column <code>procjud.t_processo_parte_procurador.cod_processo</code>. Codigo numerico atribuido ao processo para identifica-lo no banco de dados
     */
    public final TableField<TProcessoParteProcuradorRecord, Long> COD_PROCESSO = createField("cod_processo", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Codigo numerico atribuido ao processo para identifica-lo no banco de dados");
    /**
     * The column <code>procjud.t_processo_parte_procurador.cod_parte</code>. Codigo identificador da parte
     */
    public final TableField<TProcessoParteProcuradorRecord, Long> COD_PARTE = createField("cod_parte", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Codigo identificador da parte");
    /**
     * The column <code>procjud.t_processo_parte_procurador.num_procurador</code>. Numero identificador do procurador
     */
    public final TableField<TProcessoParteProcuradorRecord, Integer> NUM_PROCURADOR = createField("num_procurador", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numero identificador do procurador");

    /**
     * Create a <code>procjud.t_processo_parte_procurador</code> table reference
     */
    public TProcessoParteProcurador() {
        this("t_processo_parte_procurador", null);
    }

    /**
     * Create an aliased <code>procjud.t_processo_parte_procurador</code> table reference
     */
    public TProcessoParteProcurador(String alias) {
        this(alias, T_PROCESSO_PARTE_PROCURADOR);
    }

    private TProcessoParteProcurador(String alias, Table<TProcessoParteProcuradorRecord> aliased) {
        this(alias, aliased, null);
    }

    private TProcessoParteProcurador(String alias, Table<TProcessoParteProcuradorRecord> aliased, Field<?>[] parameters) {
        super(alias, Procjud.PROCJUD, aliased, parameters, "Relaciona os Procuradores das Partes interessadas em Processos Judiciais");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProcessoParteProcuradorRecord> getRecordType() {
        return TProcessoParteProcuradorRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TProcessoParteProcuradorRecord> getPrimaryKey() {
        return Keys.PROCESSO_PARTE_PROCURADOR_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TProcessoParteProcuradorRecord>> getKeys() {
        return Arrays.<UniqueKey<TProcessoParteProcuradorRecord>>asList(Keys.PROCESSO_PARTE_PROCURADOR_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TProcessoParteProcuradorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TProcessoParteProcuradorRecord, ?>>asList(Keys.T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK1, Keys.T_PROCESSO_PARTE_PROCURADOR__PROCESSO_PARTE_PROCURADOR_FK2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TProcessoParteProcurador as(String alias) {
        return new TProcessoParteProcurador(alias, this);
    }

    /**
     * Rename this table
     */
    public TProcessoParteProcurador rename(String name) {
        return new TProcessoParteProcurador(name, null);
    }
}
