/**
 * This class is generated by jOOQ
 */
package br.unb.sma.database.tables;


import br.unb.sma.database.Keys;
import br.unb.sma.database.Procjud;
import br.unb.sma.database.tables.records.TProcuradorRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Procuradores que atuam em Processos Judiciais
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TProcurador extends TableImpl<TProcuradorRecord> {

	/**
	 * The reference instance of <code>procjud.t_procurador</code>
	 */
	public static final TProcurador T_PROCURADOR = new TProcurador();
	private static final long serialVersionUID = 72775940;
	/**
	 * The column <code>procjud.t_procurador.num_procurador</code>. Numero identificador do procurador
	 */
	public final TableField<TProcuradorRecord, Integer> NUM_PROCURADOR = createField("num_procurador", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Numero identificador do procurador");
	/**
	 * The column <code>procjud.t_procurador.nom_procurador</code>. Nome completo do procurador
	 */
	public final TableField<TProcuradorRecord, String> NOM_PROCURADOR = createField("nom_procurador", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "Nome completo do procurador");
	/**
	 * The column <code>procjud.t_procurador.nom_procuradoria</code>. Nome da procuradoria pela qual o procurador atua
	 */
	public final TableField<TProcuradorRecord, String> NOM_PROCURADORIA = createField("nom_procuradoria", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "Nome da procuradoria pela qual o procurador atua");

	/**
	 * Create a <code>procjud.t_procurador</code> table reference
	 */
	public TProcurador() {
		this("t_procurador", null);
	}

	/**
	 * Create an aliased <code>procjud.t_procurador</code> table reference
	 */
	public TProcurador(String alias) {
		this(alias, T_PROCURADOR);
	}

	private TProcurador(String alias, Table<TProcuradorRecord> aliased) {
		this(alias, aliased, null);
	}

	private TProcurador(String alias, Table<TProcuradorRecord> aliased, Field<?>[] parameters) {
		super(alias, Procjud.PROCJUD, aliased, parameters, "Procuradores que atuam em Processos Judiciais");
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TProcuradorRecord> getRecordType() {
		return TProcuradorRecord.class;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TProcuradorRecord> getPrimaryKey() {
		return Keys.PROCURADOR_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TProcuradorRecord>> getKeys() {
		return Arrays.<UniqueKey<TProcuradorRecord>>asList(Keys.PROCURADOR_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TProcurador as(String alias) {
		return new TProcurador(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TProcurador rename(String name) {
		return new TProcurador(name, null);
	}
}
